### ISSUE TITLE
request: character hiding/masking for uiEntry fields

### ISSUE THREAD

**Issue by kruk3t** [andlabs/libui#103]
I noticed that there is no function for this specific purpose?

I'm thinking of using something like: `uiEntryOnChanged`, where I would just manipulate the displayable character with a custom one.

Well, I guess, that would also change the real input, so is there some workaround, before it is implemented?

**Comment by andlabs** [comment]
`uiNewPasswordEntry()` will be a thing in the next round. It's trivial to write anyway :)

**Comment by andlabs** [comment]
Done! Enjoy.
