### ISSUE TITLE
copying the .res file in a static Windows build is a hack that doesn't work with VS generators (was: error	MSB3073)

### ISSUE THREAD

**Issue by heijiu** [andlabs/libui#113]
error   MSB3073 command“setlocal
E:\cmake-3.5.2-win32-x86\bin\cmake.exe -E copy E:/libui-master/build/CMakeFiles/libui.dir/windows/resources.rc.res E:/libui-master/build/out/libui.res
if %errorlevel% neq 0 goto :cmEnd
:cmEnd
endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
:cmErrorLevel
exit /b %1
:cmDone
if %errorlevel% neq 0 goto :VCEnd
:VCEnd”exited with code 1.    libui   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets  133

**Comment by andlabs** [comment]
Does E:/libui-master/build/CMakeFiles/libui.dir/windows/resources.rc.res exist?

**Comment by heijiu** [comment]
E:/libui-master/build/CMakeFiles/ doesn't have windows directory

**Comment by heijiu** [comment]
but E:\libui-master\build\libui.dir\Debug have resources.res

**Comment by andlabs** [comment]
Then how did your build get that far? Can you try clearing `build/` and starting again, showing both the cmake and build logs?

**Comment by heijiu** [comment]
cmake 3.5.2 gui,i set sorce code is "E:/libui-master“,build the binaries is "E:/libui-master/build",and uncheck "BUILD_SHARE_LIBS"

**Comment by heijiu** [comment]
I've delete E:\libui-master many times

**Comment by heijiu** [comment]
find a log

E:\libui-master\build\libui.dir\Debug\libui.log


  libui.vcxproj -> E:\libui-master\build\out\Debug\libui.lib
  Error copying file "E:/libui-master/build/CMakeFiles/libui.dir/windows/resources.rc.res" to "E:/libui-master/build/out/libui.res".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: command "setlocal
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: E:\cmake-3.5.2-win32-x86\bin\cmake.exe -E copy E:/libui-master/build/CMakeFiles/libui.dir/windows/resources.rc.res E:/libui-master/build/out/libui.res
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.

**Comment by andlabs** [comment]
Ah, this is with a Visual Studio project. Where does Visual Studio keep object files?

**Comment by heijiu** [comment]
all obj files in E:\libui-master\build\libui.dir\Debug

**Comment by andlabs** [comment]
All right, so cmake really doesn't tell me where object files go; sigh...

Whatever the case, the build was successful up to that point. You just need to make sure you link the resources.rc.res in that objects folder alongside out\libui.lib.

**Comment by andlabs** [comment]
Replaced with #308.
