### ISSUE TITLE
Windows shared and MSVC static libraries fail to launch on Windows 7

### ISSUE THREAD

**Issue by SevenBits** [andlabs/libui#118]
When I download alpha 3.1, both the 32 and 64 bit shared and MSVC statically-linked executables fail to launch with the following error:

![capture](https://cloud.githubusercontent.com/assets/2482736/15967402/8c22269c-2ef5-11e6-8178-952872f05e7f.PNG)

This does not occur on alpha 3.0. It's obviously a dependency problem. The mingw statically-linked binaries work fine.

**Comment by andlabs** [comment]
Duplicate of #111
