### ISSUE TITLE
Feature request: write an uiBoxInsertAt function

### ISSUE THREAD

**Issue by parro-it** [andlabs/libui#120]
I noticed that tab widget has an useful `insertAt` method to add a child at a specified position.
A similar method is missing in box widget.
Since it already has a `delete` method, it would be a useful addition

It could be something similar to:

``` c
void uiBoxInsertAt(uiBox *b, uintmax_t before, uiControl *child, int stretchy);
```

It would be super useful because it allow one to replace a widget in a box with a different one, without resorting to remove and re-append all subsequent widgets in the box...

**Comment by andlabs** [comment]
Yes, all the containers need to have Append, InsertAt, and Delete on them; I just haven't gotten around to implementing them all yet.

**Comment by andlabs** [comment]
Now #309.
