### ISSUE TITLE
Split release binaries archives in multiple architectures

### ISSUE THREAD

**Issue by parro-it** [andlabs/libui#124]
I'm starting to figure out how I will publish [node binding lib](https://github.com/parro-it/libui-node) to NPM.

I wish to avoid recompiling `libui` on each user machine, so I thought I could download precompiled binaries for this repo releases.

However, the actual zip you produce is a bit large, because it include each architecture/ build type. People [keep complaining](https://github.com/electron/electron/issues/5482) on Electron repo about it's release size. I think a great :+1: of `libui` is it's light weight.

So, it would be difficult to split release binaries producing one for each platform? And ideally containing only one kind of build (static, dynamic, examples). Are you producing this manually or do you already have an automated process?

**Comment by andlabs** [comment]
This is manual right now. Sure, I could split them up, and drop the source code too since github already provides that as an archive. I'll try something for Alpha 4 and see if that works before closing this.

**Comment by parro-it** [comment]
Awesome :clap: ! Let me know if you need help

**Comment by andlabs** [comment]
Yeah, the use of CI to generate binaries does this.
