### ISSUE TITLE
Make uiFormAppend return the form item

### ISSUE THREAD

**Issue by emersion** [andlabs/libui#140]
Useful to be able to hide a single item for instance.

**Comment by emersion** [comment]
Or maybe just add a `uiForm{Show,Hide}Item` function?

**Comment by andlabs** [comment]
The idea, which is not implemented right now, is that hidng the control is sufficient tohide the whole item. I might return the index of the appended item from the Append functions...

**Comment by emersion** [comment]
Hiding the label when the control is hidden will be the best solution, however it seems quite difficult to implement. Any idea how to do this?

**Comment by andlabs** [comment]
On OS X I added a ChildVisibilityChanged() method to uiDarwinControl that will be used to relayout the boxes, forms, grids, etc.

On GTK+ I simply need to bind the label's `visibility` property to the control's.

On Windows I do something similar to OS X, except that an appropriate method is already there (MinimumSizeChanged()).

**Comment by emersion** [comment]
I'll close this issue since your changes fix it. :+1:

**Comment by andlabs** [comment]
Should probably return the index of the new item; reopened until then

**Comment by krakjoe** [comment]
Tag #233

**Comment by andlabs** [comment]
Merged with #309.
