### ISSUE TITLE
uiWindowSetContentSize has no effect on linux

### ISSUE THREAD

**Issue by parro-it** [andlabs/libui#150]
Property getter and onchange event are working properly.

**Comment by andlabs** [comment]
What window manager/desktop environment?

**Comment by parro-it** [comment]
I'm working on lubuntu 14 32bit

**Comment by andlabs** [comment]
Seems to work for me... What's your code?

**Comment by parro-it** [comment]
It's probably my fault. 
My window has a minimum content size of 406 x 375. I was trying to set the size in a menu to 700 x 300, so below the minimum height. I guess this is by design, so I close this...
I can successfully set it to for e.g. 800 x 600.

**Comment by andlabs** [comment]
Yeah... How minimum sizes are handled is currently left up to the underlying toolkit. Not sure what toher options I have :/

**Comment by parro-it** [comment]
That's perfectly fine I guess. 
Maybe a return error could improve usability...
