### ISSUE TITLE
Request: uiOpenDir()

### ISSUE THREAD

**Issue by apahl** [andlabs/libui#169]
Thanks a lot for this great library!
I am starting to use it from [Nim](http://nim-lang.org). 
Would it be possible to include a uiOpenDir component analogously to uiOpenFile, but allowing only the selection of directories instead of files?

Kind regards,
Axel

**Comment by andlabs** [comment]
Yes, but the dialog system is a bit of a mess right now; once I figure out how to do it better I'll add more dialogs.

**Comment by apahl** [comment]
Great!
Thanks for the fast reply.

**Comment by andlabs** [comment]
Replaced with #314.
