### ISSUE TITLE
behaviour of uiGridAppend / uiGridInsertAt when target cells are not empty

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#170]
from what I see (on linux / gtk), using uiGridAppend or uiGridIsertAt on cells that are not empty does not append / insert the new control. Is that intended? If so, some indication of whether the control was actually inserted / appended would be nice, maybe by returning a boolean indication from those functions.

**Comment by andlabs** [comment]
That is something I need to figure out. On Linux it just calls the appropriate GTK+ function, so it might be intentional there?

**Comment by gnarz** [comment]
optimally this behavior should be consistent on all supported platforms... this would also concern #135

**Comment by andlabs** [comment]
Yes, it's the Linux behavior that will decide what the other platforms will do.

**Comment by gnarz** [comment]
This will be problematic, because the bahaviour is undefined in GTK. Quoting the docs (https://developer.gnome.org/gtk3/stable/GtkGrid.html):

The behaviour of GtkGrid when several children occupy the same grid cell is undefined.

**Comment by andlabs** [comment]
Merged with #328.
