### ISSUE TITLE
onchanged / onselected / onwhatever methods should be called also for changes using the api

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#171]
many controls have on\* methods to allow to react to users changing something (like the window size, the entry's text, a selection, ...), but also have functions to change those values from within the program, without user intervention. In this case, those handlers are not called, but I think they should be.

**Comment by aoloe** [comment]
not sure... on the one side your request sounds very sensible.
on the other side, how would you then do, for the cases when you don't want to let it trigger the event? as an example when there is a risk of creating infinite loops?
i'd really like to hear an opinion from guy who have more experience than me on this topic...

**Comment by ghaberek** [comment]
I have to disagree with @gnarz. Event handlers should not be called from functions that change control properties. If this behaviour is desired, I would advise implementing something like [OnPropertyChanged](http://stackoverflow.com/a/2246837) to detect these changes.

**Comment by andlabs** [comment]
I deliberately decided the "don't trigger event for a programmatic change" way was the one to go, since in my use cases this was the behavior I wanted. I could probably add a bunch of Trigger functions or something; not sure. A full-blown property system might be doable, but even later in the future.

**Comment by andlabs** [comment]
Merged with #326.
