### ISSUE TITLE
Announce: libui-node documentation

### ISSUE THREAD

**Issue by parro-it** [andlabs/libui#172]
I drafted some pages to document `libui-node` usage:

https://github.com/parro-it/libui-node/tree/master/docs

It would be beautiful to get feedback / suggestions / correction by the community...
I also announce it here because some text/image  could be reused to document `libui` directly or even other languages bindings...

**Comment by wasamasa** [comment]
I did some independent work in the same vein for my CHICKEN wrapper:

http://wiki.call-cc.org/eggref/4/libui

What has been hugely useful was referring to the comments in the Go wrapper for some less scrutable functions.  Perhaps these should be moved to the libui itself?

**Comment by andlabs** [comment]
Closing as it's separate from libui itself and has been open for a while now.
