### ISSUE TITLE
Support ARM Builds for Raspberry Pi, NextThing CHIP, etc.

### ISSUE THREAD

**Issue by sci-phi** [andlabs/libui#179]
I am interested in using LibUI via Go, Ruby, or Python to build GUI executables for "Maker" boards with ARM SOCs like Raspberry Pi, NextThingCo CHIP (PocketCHIP especially) and whatever other IoT varietals crop up. The leading platforms are based on Debian OS variants, so Go and CMake are installable. 

How difficult do you expect it would be to modify libui to work on ARM ? Would you be willing to provide support and accept the PR if this work was attempted?

**Comment by andlabs** [comment]
libui works out of the box. For the Go package you would just need to create a `link_linux_arm.go` and respective `libui_linux_arm.a` file.

**Comment by sci-phi** [comment]
Thanks, I had a struggle with getting CMAKE > 3.1, but I finally managed to produce "libui.a" on the pocketCHIP itself using the static build advice ("cmake .. -DBUILD_SHARED_LIBS=OFF")

Is there any more documentation on the next steps I would need to take?

**Comment by andlabs** [comment]
Go into $GOPATH/github.com/andlabs/ui. You would just need to copy that `libui.a` file into the Go repository, preferably as `libui_linux_arm.a`, set up the `link_linux_arm.go` file (you can just copy `libui_linux_386.go` and edit it as appropriate), and then `go install github.com/andlabs/ui` (note the use of `go install` here, NOT `go get`).

BTW, I've switched the build system to meson, so the build instructions are slightly different. I've outlined them in the README in much clearer terms though.
