### ISSUE TITLE
Multiline Text

### ISSUE THREAD

**Issue by PaulBGD** [andlabs/libui#180]
So Labels suck for multiline text. What kind of component would we use for text? And is there a way to make it selectable?

**Comment by andlabs** [comment]
I could probably expand Label to do this now that Form exists.

**Comment by mischnic** [comment]
Multiline labels are truly needed for more complex UIs !

**Comment by parro-it** [comment]
Maybe we could use the new attributed text APIs for labels?

**Comment by andlabs** [comment]
Replaced with #309.
