### ISSUE TITLE
How to prevent running console with gui.

### ISSUE THREAD

**Issue by Losiara** [andlabs/libui#187]
When I build examples with ui project they work ok. But if I take for example - histogram and build it as separate project via cmake and dll linking, so it runs only with console on the background. How to prevent it?

**Comment by emersion** [comment]
`-H=windowsgui`

**Comment by andlabs** [comment]
That's the Go flag. The C flag depends on what compiler you use.

**Comment by Windoze345** [comment]
You need /SUBSYSTEM:WINDOWS as linker parameter.
See here: https://cmake.org/Wiki/VSConfigSpecificSettings

**Comment by andlabs** [comment]
`WIN32_EXECUTABLE FALSE` is the one. Just change it to `TRUE`.

**Comment by Windoze345** [comment]
WIN32_EXECUTABLE seems to set /SUBSYSTEM:WINDOWS internally.
But I agree it's the cleaner / better way...

**Comment by Losiara** [comment]
Thanks!

**Comment by AlexFolland** [comment]
In D using DerelictLibui, I have this in my dub.sdl to prevent the console window from opening in the background:

```
lflags "libui.lib" "/SUBSYSTEM:WINDOWS" "/ENTRY:\"mainCRTStartup\""
```

Hopefully this helps future Googlers who come across this problem.  It took me a few hours to figure this out.

**Comment by andlabs** [comment]
That won't work because Go uses gcc exclusively (it does not support MSVC). The equivalent `-mwindows` might work, but `-H=windowsgui` would be better since then the Go toolchain knows the setting.

**Comment by AlexFolland** [comment]
I'm not using Go.  I'm using D with DUB and LDC.  Also, it does work.  I have tested it here.

**Comment by andlabs** [comment]
Right, I got my projects mixed up. Sorry!

**Comment by rjopek** [comment]
Hi,

In my projects console in the background, use to control the variables
This is a very helpful thing, sometimes it's helpful
I do not consider this a mistake

**Comment by andlabs** [comment]
libui is just a DLL; it has no bearing on whether a console is opened or not. You can programmatically manipulate the console at runtime — for instance, calling `FreeConsole()` to destroy the console window — but libui won't do so itself.

**Comment by AlexFolland** [comment]
The "controlgallery" program should use WinMain in Windows.  Otherwise /ENTRY:"mainCRTStartup" is a necessary linker flag to tell MSVS' link.exe that the entry point is a C runtime "main" function instead of the expected "WinMain" function, when running with /SUBSYSTEM:WINDOWS.

Anyway, libui laggily redraws all the controls on maximization (I can see it happen in realtime), making it not suitable for my purposes.  I guess I'll use the Windows API directly for now.

**Comment by andlabs** [comment]
That's a separate issue; fixing it will require yet another tearing the backend apart and putting it back together :/
