### ISSUE TITLE
Add a function to request user attention

### ISSUE THREAD

**Issue by emersion** [andlabs/libui#191]
Currently when the app is in the background and when a new window is opened, the user is not notified about it. Add something like `uiWindowRaise` to show that a new window has appeared (on GNOME Shell a notification is displayed, on windows the taskbar button becomes orange).

**Comment by andlabs** [comment]
Those are OS features.

Related, however, is a function uiWindowRequestAttention() which will use flashing or whatever to ask the user for attention.

**Comment by emersion** [comment]
Okay, that's what I'm looking for - renaming this issue.

**Comment by emersion** [comment]
* GTK: https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-urgency-hint
* Cocoa: https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSRunningApplication_Class/#//apple_ref/occ/instm/NSRunningApplication/activateWithOptions:
* Win32: https://msdn.microsoft.com/en-us/library/windows/desktop/ms633539(v=vs.85).aspx

**Comment by andlabs** [comment]
Wrong function for Win32. FlashWindowEx() is correct.

**Comment by andlabs** [comment]
Merged with #309.
