### ISSUE TITLE
Why stop the installation

### ISSUE THREAD

**Issue by Stefanek67** [andlabs/libui#212]
As in the topic, why stop the installation ?! 
Thank you for all the answers

![14627792_10211008457749730_1853473485_n](https://cloud.githubusercontent.com/assets/22752880/19246762/428d3952-8f28-11e6-893e-68c9e49f4224.png)

**Comment by andlabs** [comment]
You are building the GTK+ version of libui on Windows instead of the Windows version. What is your environment and what is your cmake line?

**Comment by Stefanek67** [comment]
I'm doing the compilation under MSYS

**Comment by andlabs** [comment]
MSYS Shell, MinGW 32-bit Shell, or MinGW 64-bit Shell?

**Comment by Stefanek67** [comment]
MinGW 64-bit Shell

**Comment by andlabs** [comment]
And what is your cmake line? How did you install cmake? You should not be using the GTK+ version of libui on Windows.

**Comment by Stefanek67** [comment]
Nice Job , Thanks for all ....

**Comment by andlabs** [comment]
I don't understand. Did you fix the problem? If so, how?
