### ISSUE TITLE
PHP 7 binding

### ISSUE THREAD

**Issue by krakjoe** [andlabs/libui#213]
I have began work on a PHP 7 binding: https://github.com/krakjoe/ui

Before version 1.0.0, documentation will be available on php.net and the package available for download on pecl.php.net.

It may take another couple of weeks to get that far (writing documentation for php is very time consuming, it's docbook).

Would be nice to be seen in the your readme :)

**Comment by krakjoe** [comment]
Merged with pr #215

**Comment by andlabs** [comment]
So wait, what will happen after "1.0.0"? I'm not familiar with how PHP documentation works.

**Comment by krakjoe** [comment]
Right now the extension API is unstable, and could change at any time, the extension is marked experimental by the presence of the ```EXPERIMENTAL``` file, so that any early adopters know that things might change; this is just php convention.

Version 1.0.0 will be documented in the php manual, and have a stable API, and no longer be considered experimental.

Beyond that, it will be developed and maintained alongside libui, using versioning something like semver.

**Comment by andlabs** [comment]
Good to know, thanks!
