### ISSUE TITLE
The windows doesn't come to front when launching on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [andlabs/libui#218]
For example,

```
make examples
./out/controlgallery
```

works fine but the window is behind the terminal. Is this intended?

**Comment by andlabs** [comment]
See https://github.com/andlabs/libui/pull/20#issuecomment-211381971

**Comment by hajimehoshi** [comment]
Ah, I didn't know that. macOS is hard :-)

**Comment by andlabs** [comment]
I'll add something to the README about it.
