### ISSUE TITLE
When will the tree be available ?

### ISSUE THREAD

**Issue by tinycedar** [andlabs/libui#219]
Hi I am developing a App for hosts switch, and now it's implemented by walk, but walk only supports Windows, so I need a platform independent GUI library.  I tried libui before but it lacks tree widget. Could you please finish tree widget ?

![default](https://cloud.githubusercontent.com/assets/8019222/19766339/d60ed5be-9c7f-11e6-99c5-f309e88850f4.PNG)

**Comment by computerquip** [comment]
Seconded. Wanted to show some files in a collapsible tree to make a more complicated text editor. I think that's a common use case.

**Comment by dertuxmalwieder** [comment]
Third...ed.

**Comment by andlabs** [comment]
Merged with #310, though Tree (as opposed to flat Table) will come after Table.
