### ISSUE TITLE
Raspbian-Build fail

### ISSUE THREAD

**Issue by Fruchtgummi** [andlabs/libui#22]
Lets'go

go get github.com/andlabs/ui

github.com/andlabs/ui
/usr/bin/ld: cannot find -lui
collect2: error: ld returned 1 exit status

**Comment by andlabs** [comment]
As noted in the readme, you cannot merely go get this package; you have to build it in a special way because it's not finished yet. Once the next stable beta release of libui is released, I'll fix that.
