### ISSUE TITLE
build fatal error

### ISSUE THREAD

**Issue by askdaddy** [andlabs/libui#220]
When I build  libui in visual studio 14 2015 I got:

2>table.obj : error LNK2019: unresolved external symbol uiTableColumnAppendTextPart referenced in function uiTableAppendTextColumn
2>table.obj : error LNK2019: unresolved external symbol uiTableAppendColumn referenced in function uiTableAppendTextColumn
2>C:\Users\askda\git\libui\build\out\Debug\libui.dll : fatal error LNK1120: 2 unresolved externals

**Comment by andlabs** [comment]
See comment at top of README
