### ISSUE TITLE
uiTabAppend(tab, "name", NULL) behavior inconsistent across platforms

### ISSUE THREAD

**Issue by rjopek** [andlabs/libui#221]
Hi,

Windows allows to make empty tab
uiTabAppend(tab, "Basic Controls", NULL );

unix and darwin no!

If the subject is not important, please close

**Comment by andlabs** [comment]
Cleaning up those instances is a work in progress.

**Comment by rjopek** [comment]
I would chose linux, OS X, you have to be aware, that when programming a GUI for different platforms, the programmers will face with this kind of "issues". And this issues, are specific to each platform. And there can exist many many of them. So maybe is just needed to document it in the implementation.
I think about as closed.

**Comment by andlabs** [comment]
Merged with #328.
