### ISSUE TITLE
compile failed on windows by mingw-w64 

### ISSUE THREAD

**Issue by walkblank** [andlabs/libui#223]
Here is the failed information:

Error copying file "/CMakeFiles/libui.dir/windows/resources.rc.*" to "F:/libui-master/libui-master/build/out/libui.r

CMakeFiles\libui.dir\build.make:1678: recipe for target out/libui.a' failed make[2]: **\* [out/libui.a] Error 1 make[2]: **\* Deleting fileout/libui.a'
CMakeFiles\Makefile2:66: recipe for target CMakeFiles/libui.dir/all' failed make[1]: **\* [CMakeFiles/libui.dir/all] Error 2 makefile:82: recipe for targetall' failed
make: **\* [all] Error 2

**Comment by snuk182** [comment]
Confirming issue as well. Looks like cmake for windows does not accept copying multiple sources to the single target (resources.rc.* => libui.rs).

**Comment by snuk182** [comment]
Although this PR fits better: https://github.com/andlabs/libui/pull/247

**Comment by andlabs** [comment]
Merged into #308.
