### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by krakjoe** [andlabs/libui#225]
I'm wondering if audio support is a reasonable thing to expect ?

**Comment by remicollet** [comment]
indeed will be a nice idea (wrapping gstreamer on linux)

**Comment by emersion** [comment]
Maybe in a separate repo? Audio is not something I expect from a UI library, and adds many dependencies to the project.

**Comment by Impyy** [comment]
Don't libraries like [PortAudio](http://www.portaudio.com/) already do this well?

**Comment by krakjoe** [comment]
@emersion I was half expecting that kind of answer. Seems reasonable :)

@Impyy thanks for link, will read about it.

**Comment by andlabs** [comment]
I did want to make a separate library for this.

**Comment by krakjoe** [comment]
Having had a rudimentary poke around at what is available ... I think I'd like an andlabs approach to the problem ... a simple thing ...

**Comment by Someguynamedpie** [comment]
There's not much simple when it comes to audio, but you could use something like openal or if youwant lower level, SDLs audio api is simple (but I hope you know PCM)

**Comment by Surround-Sound** [comment]
Any updates?

**Comment by caspervonb** [comment]
Ancient issue but, OpenAL would be the most portable API out there at the moment. PortAudio etc exist too.

**Comment by andlabs** [comment]
Right, so this is still going to be out of scope for libui itself, so closing. There are lots of options out there in the meantime, but your mileage may vary with those.
