### ISSUE TITLE
OpenBSD build issues

### ISSUE THREAD

**Issue by jkusniar** [andlabs/libui#229]
When building static library on OpenBSD current, amd64:

```
[ 96%] Built target libui-temporary
[ 98%] Removing hidden symbols
objcopy: unrecognized option `--localize-hidden'
Usage: objcopy [option(s)] in-file [out-file]
 Copies a binary file, possibly transforming it in the process
 The options are:
...
```

Seems like OpenBSD has old version of objcopy. Removing option `--localize-hidden` from `unix/CMakeLists.txt` fixes it.

**Comment by jkusniar** [comment]
see #230

**Comment by andlabs** [comment]
The `--localize-hidden` is significant: it's the whole reason for all that complicated gobbledygook. The idea is that only the public libui API should link with the rest of the program. I want to avoid a multiple-definition error in the case that you define a function called, say, `shouldQuit()`. Is there some other way?

**Comment by jkusniar** [comment]
Don't know. This was just quick and dirty fix to get it running. Will try to find out what can by done on OpenBSD.

**Comment by jkusniar** [comment]
not supported by openbsd's version :-(

**Comment by andlabs** [comment]
Then there needs to be a replacement.

**Comment by computerquip** [comment]
Not sure how practical this is but the point of that argument is to localize hidden symbols. OpenBSD's version may not allow a convenient argument like that but it does allow you to specify each symbol via "--localize-symbols=<filename>" or "--localize-symbol=<symbolname>" per this manual page: http://man.openbsd.org/OpenBSD-current/man1/objcopy.1

**Comment by computerquip** [comment]
Also, without looking at any of the code, does declaring a function static not suffice in this case?

**Comment by andlabs** [comment]
No, because `static` would limit the function to that single file; I need to share functions across multiple files without exporting them.

It'd be great if I could autogenerate such a symbols list from the toplevel `.h` files...

**Comment by DemiMarie** [comment]
@andlabs A program using libclang might be up to the task.

**Comment by andlabs** [comment]
I'm going to add `uipriv` to any private function instead, so I can get rid of any and all static library hacks.

**Comment by andlabs** [comment]
Replaced with #308.
