### ISSUE TITLE
Apple OSX cannot rerun cmake

### ISSUE THREAD

**Issue by wtfbbqhax** [andlabs/libui#231]
# System details
* macOS Sierra
* Version 10.12
* cmake version 3.6.2

# Steps to reproduce

```bash
mkdir build
cd build
cmake ..
cmake ..
```

# Actual result

```
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.8' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:30 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/viroemer/Devel/libui/libui/build/CMakeFiles/CMakeOutput.log".
```

# Work around

Commenting out `set(CMAKE_OSX_DEPLOYMENT_TARGET "10.8")` in the top CMakeLists.txt seems to make this issue go away- If I get time I'll investigate a complete fix- for now I'm just evaluating libui for my tasks.

**Comment by andlabs** [comment]
Strnage issue. Unfortunately, I don't know enough about cmake myself to know what's going on. The deployment target being set is important — if you build without the setting on 10.12, the binary will only run on 10.12.

**Comment by mischnic** [comment]
Works with master and cmake 3.10.2.

**Comment by andlabs** [comment]
I plan on replacing cmake. Keep this open for now.

**Comment by andlabs** [comment]
The switch to meson has happened; closing.
