### ISSUE TITLE
where is uiOpenGLArea?

### ISSUE THREAD

**Issue by sonoro1234** [andlabs/libui#242]
Hi,

I saw an anouncement of uiOpenGLArea but it is nowhere in the code.
Is there a way to create an openGL context?

victor bombi

**Comment by andlabs** [comment]
What announcement did you read? That feature is still being developed by someone else, and they've been too busy to complete it right now.

**Comment by sonoro1234** [comment]
https://github.com/andlabs/libui/blob/master/ANNOUNCE.md

but I see it was: The next packaged release will introduce: 

Thanks
