### ISSUE TITLE
Heavy flickering and slow tab changing on Windows 10

### ISSUE THREAD

**Issue by qoh** [andlabs/libui#243]
http://i.imgur.com/wqrIt4c.gifv

32-bit build from VS 2015, running on a i5-4200M and Intel HD Graphics 4600
Is this known behavior? Why does this happen?

**Comment by andlabs** [comment]
Duplicate of https://github.com/andlabs/ui/issues/184

**Comment by andlabs** [comment]
On second thought I'll keep this open in the meantime.

**Comment by zhaozg** [comment]
https://github.com/andlabs/ui/issues/184#issuecomment-242686886 works for me fine.

**Comment by andlabs** [comment]
Yes; I did not apply that fix specifically because it makes things look ugly. The proper fix would require yet another major upheaval as to how uiControl and uiWindowsControl work/.

**Comment by andlabs** [comment]
Replaced with #311.
