### ISSUE TITLE
Another libui wrapper in python.

### ISSUE THREAD

**Issue by Yardanico** [andlabs/libui#244]
https://github.com/TiberiumPY/pylibui-cffi
Based on pylibui, but has cleaner property set/get interface+cffi instead of ctypes.

**Comment by TiberiumPY** [comment]
Compare this (pylibui-cffi)
`python
from pylibui.core import App
from pylibui.controls import Window


class MyWindow(Window):

    def on_close(self, data):
        super().on_close(data)
        app.stop()


app = App()

window = MyWindow('Window', 800, 600)
window.margined = True
window.show()

app.start()
app.close()`

to this:
`python
from pylibui.core import App
from pylibui.controls import Window


class MyWindow(Window):

    def onClose(self, data):
        super().onClose(data)
        app.stop()


app = App()

window = MyWindow('Window', 800, 600)
window.setMargined(True)
window.show()

app.start()
app.close()`

Yeah, there's more changes under the hood

**Comment by Armored-Dragon** [comment]
Nice, but there's not really much point in this since ctypes is more portable than cffi. Maybe you could just  port the cleaner property interface to ctypes

**Comment by andlabs** [comment]
Putting it up anyway. Hopefully people who are more familiar with Python libraries than I am can judge which is appropriate for them.
