### ISSUE TITLE
Static library appears broken on OSX

### ISSUE THREAD

**Issue by grumblygibson** [andlabs/libui#245]
The library compiles just fine, but when I try to link with an example then I get:
```
$ cc -o main main.c libui.a
Undefined symbols for architecture x86_64:
  "_CFArrayGetCount", referenced from:
      _uiDrawFontFamiliesNumFamilies in libui.a(libui-combined.o)
<redacted>

**Comment by andlabs** [comment]
When using the static library, you have to explicitly link against the system libraries as well:

```
cc -o main main.c libui.a -framework Foundation -framework AppKit
```

**Comment by grumblygibson** [comment]
Thanks! You identified my confusion. Sorry for the erroneous 'issue'.
