### ISSUE TITLE
nuklear

### ISSUE THREAD

**Issue by jfcg** [andlabs/libui#246]
How does libui compare with https://github.com/vurtun/nuklear ?

**Comment by aoloe** [comment]
as far as i understand it:

- libui uses the native widgets from your OS
- nuklear draws its own widgets (and looks the same on every OS)

depending on the type of software you're programming, you'll prefer the first or the latter approach.

**Comment by andlabs** [comment]
This is not an actionable issue, so I will close it. I don't know if or when I will ever feel a need to start a general discussion forum for libui...
