### ISSUE TITLE
Saving Area state on Draw

### ISSUE THREAD

**Issue by mpiannucci** [andlabs/libui#251]
When Draw is called, the entire `uiArea` seems to be cleared instead of appended to. Is it currently possible with libui to save the current context or surface so the state can be used the next time a redraw is triggered?

For background, I am trying to make a simple drawing app and I am trying to avoid keeping track of the entire point cloud of the current drawing.

**Comment by andlabs** [comment]
The uiAreaDrawParams clipping rectangle is supposed to be the current redraw area, but there are some implementation details I am exposing and ensuring compatibility for. I need to rework those again sometime, because in retrospect that wasn't a good idea...

**Comment by mpiannucci** [comment]
Okay makes sense. So in its current status the uiAreaDrawParams clipping rectangle is drawn fresh before Draw is called on the uiAreaHandler, wiping away any previous draws?

**Comment by andlabs** [comment]
After a window resize or a call to `uiAreaQueueRedrawAll()`, yes. The OS is free to choose whether we should redraw a portion of the area only; I honor this already. I will also add a `uiAreaQueueRedraw()` function that lets you pass a rectangle to add to the overall redraw area for the next redraw cycle.

**Comment by mpiannucci** [comment]
Great thank you!

**Comment by andlabs** [comment]
Merged with #329.
