### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by apahl** [andlabs/libui#252]
Thanks a lot for this great project.
Could you maybe prepare another release, esp. with Windows binaries?
Unfortunately, I can not build the shared lib for Windows myself, since the Linux cross-compilation toolchain only builds the static lib.

Many thanks in advance.

**Comment by rjopek** [comment]
Hi apahl,
binary download for libui (Windows)
https://github.com/rjopek/hbui/tree/master/docs/tutorial#binary-download

**Comment by apahl** [comment]
Cool!
Thanks a lot.

**Comment by andlabs** [comment]
Keep in mind that building from master will give you unfinished and unstable API and ABI, and you'll need to rebuild when there are changes. Developing the stuff I promised for the next stable release is taking time; sorry again for the delay.

**Comment by apahl** [comment]
Thanks again.
And, no worries. This is a great lib that has brought cross-platform development to another level, in my view.
Your efforts are very much appreciated.
