### ISSUE TITLE
press ENTER in uiEntry control will cause crash

### ISSUE THREAD

**Issue by zhaozg** [andlabs/libui#255]
#Env

- Win10 64bits
- MSVC2015 build 32bit libui

#how to catch

1. launch controlgallery.exe
2. focus on any one of uiEntry/uiSearchEntry/uiPasswordEntry
3. Press ENTER
4. you got it

same thing happed in https://github.com/zhaozg/lui/tree/master/examples

**Comment by andlabs** [comment]
This should already have been reported elsewhere, with a pending fix...

**Comment by ocornut** [comment]
@zhaozg This PR fixed it for me https://github.com/andlabs/libui/pull/202

**Comment by iKlsR** [comment]
@ocornut Curious, what are you using this for? Something new or just poking around?

**Comment by ocornut** [comment]
@iKlsR I wanted to make a simple "launcher" for my game that would appear before booting or in safe-mode, to select monitor, resolution, etc.

**Comment by zhaozg** [comment]
@ocornut thanks, and #202 works fine.

**Comment by andlabs** [comment]
This should be fixed in libui upstream now.

**Comment by zhaozg** [comment]
I GOT IT
