### ISSUE TITLE
how to build a libui.dll, that can work in xp ?

### ISSUE THREAD

**Issue by huangyy** [andlabs/libui#257]
I build libui.dll by vs 2013 (use v120_xp). it ok, but run a app that write by dlang derelict-libui in xp, app not work, it show "The procedure entry point getlocaleinfoex could not be located in the dynamic link library KERNEL32.dll".
app works in windows 10. so , I think libui.dll is not work in xp. how to build it that can work in xp ?

**Comment by duckbrain** [comment]
From the README.md of this project:

> Runtime Requirements
> 
> - Windows: Windows Vista SP2 with Platform Update or newer
> - Unix: GTK+ 3.10 or newer
> - Mac OS X: OS X 10.8 or newer

I think you're out of luck with XP. [GetLocaleInfoEx](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318103(v=vs.85).aspx) was mentioned in your error and was introduced in Windows Vista. 

If you wanted to fix it for your own build you could try to get libui to not need that call. The Microsoft documentation says that GetLocaleInfo does something similar, but works on earlier version of Windows. I have no idea why that decision was made for this project, and there may be many other issues with compiling for XP. I don't recommend it.

**Comment by rjopek** [comment]
Hi, 
In order to build a Windows XP compatible EXE with VS 2015 (or VS 2012 / VS 2013) you have to use the v140_xp Platform Toolset rather than the default v140 Platform Toolset.

**Comment by andlabs** [comment]
libui does not support Windows XP, sorry.
