### ISSUE TITLE
Cannot get selected radiobutton

### ISSUE THREAD

**Issue by benpye** [andlabs/libui#26]
I don't know if I am missing something but I've looked at the go library too, and there appears to be no way to get the current selected radio button?

**Comment by andlabs** [comment]
Right, I haven't implemented that yet. Sorry! I'll add that later today, when I redo radio buttons a bit (they're using deprecated features on OS X and are slightly broken on Windows, so I might as well fix them all at once).

**Comment by benpye** [comment]
Ah okay, that makes sense. There are a couple controls that appears incomplete (datetimepicker) is another, but I guess you know, only became more obvious as I've been going through wrapping each control and seeing those that seem to be missing features.

**Comment by andlabs** [comment]
Done.
