### ISSUE TITLE
Library status?

### ISSUE THREAD

**Issue by acisternino** [andlabs/libui#260]
I need a GUI for my [Crystal](https://crystal-lang.org/) program and I would like to contribute to the language bindings available [here](https://github.com/Fusion/libui.cr).

Unfortunately libui development seems a bit stalled. Only a few commits since July 2016 and nothing at all since Dec, 1st.

Can anyone comment on the status of this library or provide a roadmap of some sort?

In any case thanks a lot for an awesome piece of software!

**Comment by wareya** [comment]
Development is happening on a non-master branch: https://github.com/andlabs/libui/tree/utflib-and-attrstr

Take care!

**Comment by andlabs** [comment]
Yes, I have started using feature branches.

**Comment by acisternino** [comment]
@andlabs, @wareya thanks a lot for the info, I'll keep an eye on the branches.
