### ISSUE TITLE
Dynamic Combobox

### ISSUE THREAD

**Issue by hyperum** [andlabs/libui#264]
As of right now it seems that the combobox doesn't really support a dynamic array of options. I am trying to use it with an array that constantly gets resized and with elements that constantly change. However, the combobox does not have a function to clear its list of options.

**Comment by ernierasta** [comment]
Hi, look here, you can do the same in c: https://github.com/andlabs/ui/issues/204

**Comment by andlabs** [comment]
Yes, I need to finish up the APIs on the basic controls.

**Comment by cody271** [comment]
- Looks like what we're missing from `uiCombobox` API is easy to fix:
```
_UI_EXTERN void uiComboboxDelete(uiCombobox *c, int index);
```

- Not sure about `uiEditableCombobox` API ..
> // TODO what do we call a function that sets the currently selected item and fills the text field with it? editable comboboxes have no consistent concept of selected item

**Comment by andlabs** [comment]
The comment in uiEditableCombobox is unrelated; it would still be a `uiEditableComboboxDelete()`.

**Comment by cody271** [comment]
So we just need these two API functions ?
```
_UI_EXTERN void uiComboboxDelete(uiCombobox *c, int index);
_UI_EXTERN void uiEditableComboboxDelete(uiEditableCombobox *c, int index);
```

**Comment by andlabs** [comment]
Yes, and `InsertAt` as well.

**Comment by cody271** [comment]
Looks like this issue has some duplicates, merge with #126 and #227. Also maybe #228.

**Comment by andlabs** [comment]
Replaced with #309.
