### ISSUE TITLE
Document the possibility to write / attach custom native controls

### ISSUE THREAD

**Issue by snuk182** [andlabs/libui#268]
[For instance](http://www.scintilla.org/ScintillaDoc.html)

**Comment by andlabs** [comment]
Yes, you can do this by creating your own uiControl-derived types. This is a platform-specific thing that I intend on fully documenting, but for now you can look at the implementations of many of the current controls and the `ui_OS.h` files.

**Comment by andlabs** [comment]
Merged with #317.
