### ISSUE TITLE
the 'out' folder is empty after cmake success.

### ISSUE THREAD

**Issue by AtlanticF** [andlabs/libui#272]
the problem like the title.
=== This is my cmake info ===
smf@smf-OptiPlex-3040:/usr/local/libui$ sudo cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.18.9
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/libui
=== End ===

But the 'out' folder is empty. so why?

**Comment by andlabs** [comment]
Because cmake only prepares a build environment. After cmake runs, you actually need to build libui. If cmake produced a Makefile, then run `make` to actually build libui.

**Comment by AtlanticF** [comment]
@andlabs OK, I got it. I just found out i'm not run `make`. thank you so much.
