### ISSUE TITLE
Please write documentation.

### ISSUE THREAD

**Issue by Qwerp-Derp** [andlabs/libui#278]
I know that it says on the README that documentation isn't ready yet, but I really want to use this tool as it is right now. Can you please please please provide at least some documentation on the most essential parts of LibUI so we don't have to fish through a C header file for a function?

**Comment by adrian5** [comment]
@andlabs If down the line you have documentation drafts that you feel need looking over (or polishing), I'd gladly offer my help. Unfortunately, I currently don't know enough about the innards of libui to write items from scratch.

I really like the idea behind this project.

**Comment by bcampbell** [comment]
I've started adding API reference documentation into ui.h
in my [docs branch](https://github.com/andlabs/libui/compare/master...bcampbell:docs).
I've been pulling comments over from the equivalent godoc comments in the golang bindings, adding C-specific info where relevant.
@andlabs: let me know if this is useful - if so I'll push on and do the rest of the calls.

**Comment by andlabs** [comment]
Merged with #317.
