### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by justasmalinauskas** [andlabs/libui#280]
Hi, I saw your project few weeks ago and I would use it in my projects. I saw that you feel unmotivated. Maybe you could set up a donation page though paypal so at least I'm could donate some money to make you motivated to develop this project?

**Comment by andlabs** [comment]
I've been asked this a couple of times already, and I am considering setting up something, but I'm not 100% sure...

As far as motivation goes, I am starting to get it back now. Thanks for your concern in the meantime; I appreciate it :)

**Comment by mulianov** [comment]
https://www.reddit.com/r/getdisciplined/comments/2scdwz/discussion_screw_motivation_what_you_need_is/

8 сент. 2017 г. 7:24 PM пользователь "Pietro Gagliardi" <
notifications@github.com> написал:

**Comment by lukechilds** [comment]
@andlabs Please do it! I would happily donate to an Open Collective, I really want this to exist.

**Comment by lailton** [comment]
+1

**Comment by andlabs** [comment]
Thanks everyone, but I've decided to decline accepting donations at present.
