### ISSUE TITLE
crash on escape

### ISSUE THREAD

**Issue by petelomax** [andlabs/libui#283]
I have ported a libui language binding to my own, Phix, and got everything apparently working apart from one thing: while the 64-bit version seems fine, when I press escape on the 32-bit version it crashes with an int3 in KERNELBA, with this on the stack:

000DFCE8   6EBF154F  RETURN to libui32g.6EBF154F from libui32g.6EBFA6F0 
000DFCEC   6EC11DC4  ASCII "Z:\Documents\Projects\libui\windows\menu.cpp" 
000DFCF0   6EC12168  ASCII "296" 
000DFCF4   6EC12158  ASCII "runMenuEvent" 
000DFCF8   6EC0C744  ASCII "POSSIBLE IMPLEMENTATION BUG; CONTACT ANDLABS:" 
000DFCFC   6EC12130  ASCII "unknown menu ID %hu in runMenuEvent()" 
000DFD00   000DFD18 
000DFD04   6EC03206  RETURN to libui32g.6EC03206 from libui32g.6EBF1530 
000DFD08   6EC11DC4  ASCII "Z:\Documents\Projects\libui\windows\menu.cpp" 
000DFD0C   6EC12168  ASCII "296" 
000DFD10   6EC12158  ASCII "runMenuEvent" 
000DFD14   6EC12130  ASCII "unknown menu ID %hu in runMenuEvent()" 

Why it would be looking for a menu entry because I pressed escape is beyond me. Is there anything I can do about deliberately catching/handling that escape?

Pete

**Comment by andlabs** [comment]
There's a PR I need to merge that fixes this.

**Comment by zhaozg** [comment]
https://github.com/andlabs/libui/issues/255

**Comment by PaluMacil** [comment]
Fixed! This is ready to close.
