### ISSUE TITLE
Menu items

### ISSUE THREAD

**Issue by rawsh** [andlabs/libui#284]
On linux, these items are in a app menu. In windows, on the app right click. Not sure about mac. Can you add support for these? E.g.

![screenshot from 2017-11-11 10-02-27](https://user-images.githubusercontent.com/7035671/32691051-9b859ae0-c6c7-11e7-9286-010422ce068b.png)

**Comment by andlabs** [comment]
The GNOME app menu is a special GTK+-specific feature; not all desktop environments provide it. libui provides menus via a standard menubar (but I want to redo its API).

**Comment by rawsh** [comment]
Ok, makes sense. Thanks for looking at all my issues, this is a great platform so far
