### ISSUE TITLE
Getting value from uiDateTimePicker?

### ISSUE THREAD

**Issue by LeoTindall** [andlabs/libui#295]
How would I go about getting the time and date value from a uiDateTimePicker?

**Comment by andlabs** [comment]
I haven't written that part yet, sorry. I do need to get back to rounding out the regular controls.

**Comment by LeoTindall** [comment]
No worries! Just wanted to make sure I wasn't missing something.

I appreciate all the hard work you've done in this project so far. Thanks!

**Comment by andlabs** [comment]
Will keep open as a reminder anyway.

**Comment by cody271** [comment]
Welcome back, @andlabs! Proper handling of date and time can be really tricky, but I can work on this issue. Can we use `struct tm` from the C standard library, or do we need a `uiDateTime` struct?

What do you think of this for the `ui.h` API?
```
#include <time.h>

_UI_EXTERN void uiDateTimePickerTime(uiDateTimePicker *d, struct tm *time);
_UI_EXTERN void uiDateTimePickerSetTime(uiDateTimePicker *d, struct tm *time);
_UI_EXTERN void uiDateTimePickerOnChanged(uiDateTimePicker *d, void (*f)(uiDateTimePicker *, void *), void *data);
```

**Comment by andlabs** [comment]
I don't know, but I do know uiDateTimePicker won't handle any actual time stuff, and should just return the time as the user has entered it. Programs would be responsible for properly doing time zone calculations.

**Comment by cody271** [comment]
Cool I will start with `struct tm` then. Does that API otherwise look acceptable to you before I starting implementing?

**Comment by andlabs** [comment]
It does.

I'm not sure if `<time.h>` should be included or `struct tm;` should be predeclared.

Also when filling a `struct tm`:

- `tm_wday` and `tm_yday` should be ignored; documentation should say their values should be undefined
- `tm_isdst` should be negative to signify "unknown"; this should be documented

When reading from a `struct tm` it *might* be safe to just ignore those three fields; IDK.

I'm not particularly thrilled that there is no UTC `mktime()`, nor one that allows you to specify an arbitrary time zone, but whatever.

**Comment by andlabs** [comment]
Replaced with #297.
