### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by l41lt0n** [andlabs/libui#296]
Hi,

I am trying to compile from Mac High Sierra but I got theses errors:
Scanning dependencies of target libui
[  1%] Building C object CMakeFiles/libui.dir/common/attrlist.c.o
In file included from /Developer/git/libui-2/common/attrlist.c:2:
In file included from /Developer/git/libui-2/common/../ui.h:490:
/Developer/git/libui-2/./ui_attrstr.h:34:48: error: unknown type name 'uiDrawTextLayout'
_UI_EXTERN void uiDrawTextLayoutLineGetMetrics(uiDrawTextLayout *tl, int line, uiDrawTextLayoutLineMetrics *m);
                                               ^
/Developer/git/libui-2/./ui_attrstr.h:46:41: error: unknown type name 'uiDrawTextLayout'
_UI_EXTERN void uiDrawTextLayoutHitTest(uiDrawTextLayout *tl, double x, double y, size_t *pos, int *line);
                                        ^
/Developer/git/libui-2/./ui_attrstr.h:59:54: error: unknown type name 'uiDrawTextLayout'
_UI_EXTERN double uiDrawTextLayoutByteLocationInLine(uiDrawTextLayout *tl, size_t pos, int line);
                                                     ^
/Developer/git/libui-2/./ui_attrstr.h:61:67: error: unknown type name 'uiDrawTextLayout'
_UI_EXTERN void uiDrawCaret(uiDrawContext *c, double x, double y, uiDrawTextLayout *layout, size_t pos, int *line);
                                                                  ^
/Developer/git/libui-2/./ui_attrstr.h:68:51: error: unknown type name 'uiDrawFontDescriptor'
_UI_EXTERN void uiFontButtonFont(uiFontButton *b, uiDrawFontDescriptor *desc);
                                                  ^
In file included from /Developer/git/libui-2/common/attrlist.c:3:
/Developer/git/libui-2/common/uipriv.h:73:37: error: unknown type name 'uiAttributedString'
extern const uint16_t *attrstrUTF16(uiAttributedString *s);
                                    ^
/Developer/git/libui-2/common/uipriv.h:74:31: error: unknown type name 'uiAttributedString'
extern size_t attrstrUTF16Len(uiAttributedString *s);
                              ^
/Developer/git/libui-2/common/uipriv.h:75:34: error: unknown type name 'uiAttributedString'
extern size_t attrstrUTF8ToUTF16(uiAttributedString *s, size_t n);
                                 ^
/Developer/git/libui-2/common/uipriv.h:76:39: error: unknown type name 'uiAttributedString'
extern size_t *attrstrCopyUTF8ToUTF16(uiAttributedString *s, size_t *n);
                                      ^
/Developer/git/libui-2/common/uipriv.h:77:39: error: unknown type name 'uiAttributedString'
extern size_t *attrstrCopyUTF16ToUTF8(uiAttributedString *s, size_t *n);
                                      ^
/Developer/git/libui-2/common/uipriv.h:81:61: error: unknown type name 'uiAttributeSpec'
extern void attrlistInsertAttribute(struct attrlist *alist, uiAttributeSpec *spec, size_t start, size_t end);
                                                            ^
/Developer/git/libui-2/common/uipriv.h:84:61: error: unknown type name 'uiAttribute'
extern void attrlistRemoveAttribute(struct attrlist *alist, uiAttribute type, size_t start, size_t end);
                                                            ^
/Developer/git/libui-2/common/uipriv.h:87:53: error: unknown type name 'uiAttributedString'
extern void attrlistForEach(struct attrlist *alist, uiAttributedString *s, uiAttributedStringForEachAttributeFunc f, void *data);
                                                    ^
/Developer/git/libui-2/common/uipriv.h:87:76: error: unknown type name 'uiAttributedStringForEachAttributeFunc'
extern void attrlistForEach(struct attrlist *alist, uiAttributedString *s, uiAttributedStringForEachAttributeFunc f, void *data);
                                                                           ^
/Developer/git/libui-2/common/uipriv.h:102:70: error: unknown type name 'uiDrawTextLayout'
extern void drawTextBackground(uiDrawContext *c, double x, double y, uiDrawTextLayout *layout, size_t start, size_t end, uiDrawBrush *bru...
                                                                     ^
/Developer/git/libui-2/common/attrlist.c:16:2: error: unknown type name 'uiAttributeSpec'
        uiAttributeSpec spec;
        ^
/Developer/git/libui-2/common/attrlist.c:31:41: error: unknown type name 'uiAttributeSpec'
static void attrSetSpec(struct attr *a, uiAttributeSpec *spec)
                                        ^
/Developer/git/libui-2/common/attrlist.c:33:14: warning: unused variable 'family' [-Wunused-variable]
        const char *family;
                    ^
/Developer/git/libui-2/common/attrlist.c:34:8: warning: unused variable 'familyCopy' [-Wunused-variable]
        char *familyCopy;
              ^
/Developer/git/libui-2/common/attrlist.c:330:46: error: unknown type name 'uiAttributeSpec'
static int specsIdentical(struct attr *attr, uiAttributeSpec *spec)
                                             ^
/Developer/git/libui-2/common/attrlist.c:362:54: error: unknown type name 'uiAttributeSpec'
void attrlistInsertAttribute(struct attrlist *alist, uiAttributeSpec *spec, size_t start, size_t end)
                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make[2]: *** [CMakeFiles/libui.dir/common/attrlist.c.o] Error 1
make[1]: *** [CMakeFiles/libui.dir/all] Error 2
make: *** [all] Error 2

**Comment by andlabs** [comment]
utflib-and-attrstr cannot be built right now, sorry.

**Comment by l41lt0n** [comment]
@andlabs 
Ok, Thank you.
