### ISSUE TITLE
WebView ( darwin - MacOSx )

### ISSUE THREAD

**Issue by l41lt0n** [andlabs/libui#298]
I am working in a simple application special for mac and I need to create a webview
on the window. but I not found way to do it.

Can you tell me, how can I do that?

Thanks

**Comment by parro-it** [comment]
There isn't a webview widget in libui at the moment.

**Comment by andlabs** [comment]
If you are only targeting OS X you can write your own that wraps around WebKit.framework; look at how controls are implemented in libui itself, and use `ui_darwin.h`.

**Comment by l41lt0n** [comment]
@andlabs,
Exactly. I am new with objectiveC, is possible provide a small example how to create this object "WebView and add to a window"?

Thanks a lot.

**Comment by cody271** [comment]
@l41lt0n Can you tell us more about your use case?
While a hybrid app with both libui and Objective-C is certainly possible, you might be better off with a more mature library. Qt perhaps? QtWebKit is [very easy to use](https://stackoverflow.com/questions/14616342/example-code-for-a-simple-web-page-browser-using-webkit-qt-in-c).

@andlabs I think a real `uiWebView` control is probably out of scope for the foreseeable future. Thoughts?

**Comment by l41lt0n** [comment]
Hi @cody271  and @andlabs,

I am using part my app hybrid and another part with libui.

I would like to continue to use libui, so, if I can to create a webview inside window. it will solve all that I need. :D

Note, my target is only for MacApp.

Thanks for reply.

**Comment by PaluMacil** [comment]
I think of libui as an analog to TKinter in Python. If I don't need webview and tables (which are in process for libui actually), then I use libui (technically I use ui since I write Go, which uses libui in turn). If I need more, I use wxGo. I don't know if wxWidgets has something for you since I don't know if you're using libui directly or in another language, but Qt has something in all big languages. 

It would be interesting to add a webview to libui. One problem is keeping libui small. It weighs in so much smaller than Qt and wxWidgets that I love it whenever it fits. It might be able to stay small if you call out to another framework, and @zserge has written a nice C and Go wrapper combo, so it's possible.

**Comment by andlabs** [comment]
WebView is not out of scope for libui in general, but will probably require too big of an API to be in scope for this specific repository. I will probably wind up making a libui-webview repository, which will produce a separate library to use instead. The real issue is deciding whether it would be better to use the same engine everywhere or the engines that come with the OS in question, and if the former, which engine to use.

**Comment by parro-it** [comment]
I remember months ago I found https://github.com/pojala/electrino
that try to implements a webview widget using every engine default OS.

It could be interesting to give it a look... At the time it works only on macOS, but others platforms were planned...

**Comment by PaluMacil** [comment]
@parro-it  https://github.com/zserge/webview seems to have more documentation and **much** more recent activity. It's also implemented in both C and Go, so I would recommend it

**Comment by l41lt0n** [comment]
@PaluMacil,

I don't see reason to go to another tools if is possible to do with libui, and I dont think that it will make the source big at all. and the my question here is not to add to project, but only a way for me be able to continue using this excellent project with this PLUGS and exccelent feature "webview".
I dont like Qt and wxWidget for the dependence of 3rds files. but thanks for tip.
I will to verify the zserge.

@andlabs 
Thank you for the interest to help, It will be very useful not only for me, but I believe that others person will like this feature too :) 

@parro-it 
Thanks, I will to check

Thanks guys, all help here is welcome.

**Comment by PaluMacil** [comment]
@l41lt0n My zserge/webview recommendation was for possible feature implementation into libui as a longer term solution. The electrino recommendation might work for you, since it's Objective C, but I don't write objective c, so I'm limited in commenting on that library.

**Comment by l41lt0n** [comment]
@PaluMacil,

Excellent, I will to verify

Thanks

**Comment by cody271** [comment]
@l41lt0n Take a look at this gist [here](https://gist.github.com/cody271/6b4d83ca0ceb55f98a387c5630abf22f). This should help get you started!

**Comment by l41lt0n** [comment]
@cody271,

Thank you!!!

I have tried to compile but I got a lot of errors, but I will to verify. of course it will to help :D

Thanks

**Comment by l41lt0n** [comment]
@cody271 

Thank you!!!

Works like a charm!

![screen shot 2018-02-28 at 11 01 56 pm](https://user-images.githubusercontent.com/32529405/36823333-74b3436c-1cdb-11e8-9742-b3ea02a03b4a.png)

**Comment by l41lt0n** [comment]
@cody271,

Can you tell me the way to add this event to webview

```
WKNavigationDelegate, WKUIDelegate, WKScriptMessageHandler
```

I would like to verify this function to identify part navegation:


```

- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
    NSURL *url = navigationAction.request.URL;
    
    if ([url.host hasSuffix:@"test.com"]) {
        decisionHandler(WKNavigationActionPolicyAllow);
    } else {
        decisionHandler(WKNavigationActionPolicyCancel);
        [[NSWorkspace sharedWorkspace] openURL:url];
    }
}
@end

```

**Comment by cody271** [comment]
@l41lt0n There is no delegate class in the simple example I wrote, so you'll have to write one.

[This book](https://github.com/xstpl/Livros-1/raw/master/Programa%C3%A7%C3%A3o%20com%20Objective-C.pdf) might help you learn more Objective-C.

**Comment by l41lt0n** [comment]
Thank you
Em seg, 5 de mar de 2018 às 2:32 AM, cody271 <notifications@github.com>
escreveu:
