### ISSUE TITLE
Can't use the library system-wide

### ISSUE THREAD

**Issue by amar-laksh** [andlabs/libui#31]
So I ran: 
make install

I am trying to use the library to run a program. Please help. I really love this project.
Even the simplest setup:

gcc -L. -l:libui.so \`pkg-config --cflags --libs gtk+-3.0\` -o a.out main.c

gives:

/tmp/ccXi6gxB.o: In function `onClosing':
main.c:(.text+0x1b): undefined reference to `uiControlDestroy'
main.c:(.text+0x20): undefined reference to `uiQuit'
/tmp/ccXi6gxB.o: In function `shouldQuit':
main.c:(.text+0x42): undefined reference to `uiControlDestroy'
/tmp/ccXi6gxB.o: In function `openClicked':
main.c:(.text+0x6c): undefined reference to `uiOpenFile'
main.c:(.text+0x90): undefined reference to `uiMsgBoxError'
main.c:(.text+0xaa): undefined reference to `uiMsgBox'
main.c:(.text+0xb6): undefined reference to `uiFreeText'
/tmp/ccXi6gxB.o: In function `saveClicked':
main.c:(.text+0xdb): undefined reference to `uiSaveFile'
main.c:(.text+0xff): undefined reference to `uiMsgBoxError'
main.c:(.text+0x119): undefined reference to `uiMsgBox'
main.c:(.text+0x125): undefined reference to `uiFreeText'
/tmp/ccXi6gxB.o: In function `update':
main.c:(.text+0x149): undefined reference to `uiSpinboxSetValue'
main.c:(.text+0x15f): undefined reference to `uiSliderSetValue'
main.c:(.text+0x176): undefined reference to `uiProgressBarSetValue'
/tmp/ccXi6gxB.o: In function `onSpinboxChanged':
main.c:(.text+0x197): undefined reference to `uiSpinboxValue'
/tmp/ccXi6gxB.o: In function `onSliderChanged':
main.c:(.text+0x1c0): undefined reference to `uiSliderValue'
/tmp/ccXi6gxB.o: In function `main':
main.c:(.text+0x1f4): undefined reference to `uiInit'
main.c:(.text+0x228): undefined reference to `uiFreeInitError'
main.c:(.text+0x23c): undefined reference to `uiNewMenu'
main.c:(.text+0x251): undefined reference to `uiMenuAppendItem'
main.c:(.text+0x26b): undefined reference to `uiMenuItemOnClicked'
main.c:(.text+0x27c): undefined reference to `uiMenuAppendItem'
main.c:(.text+0x296): undefined reference to `uiMenuItemOnClicked'
main.c:(.text+0x2a2): undefined reference to `uiMenuAppendQuitItem'
main.c:(.text+0x2b5): undefined reference to `uiOnShouldQuit'
main.c:(.text+0x2bf): undefined reference to `uiNewMenu'
main.c:(.text+0x2d4): undefined reference to `uiMenuAppendCheckItem'
main.c:(.text+0x2e4): undefined reference to `uiMenuAppendSeparator'
main.c:(.text+0x2f5): undefined reference to `uiMenuAppendItem'
main.c:(.text+0x305): undefined reference to `uiMenuItemDisable'
main.c:(.text+0x311): undefined reference to `uiMenuAppendPreferencesItem'
main.c:(.text+0x31f): undefined reference to `uiNewMenu'
main.c:(.text+0x334): undefined reference to `uiMenuAppendItem'
main.c:(.text+0x344): undefined reference to `uiMenuAppendAboutItem'
main.c:(.text+0x361): undefined reference to `uiNewWindow'
main.c:(.text+0x37c): undefined reference to `uiWindowSetMargined'
main.c:(.text+0x395): undefined reference to `uiWindowOnClosing'
main.c:(.text+0x39a): undefined reference to `uiNewVerticalBox'
main.c:(.text+0x3af): undefined reference to `uiBoxSetPadded'
main.c:(.text+0x3c5): undefined reference to `uiWindowSetChild'
main.c:(.text+0x3ca): undefined reference to `uiNewHorizontalBox'
main.c:(.text+0x3df): undefined reference to `uiBoxSetPadded'
main.c:(.text+0x3f7): undefined reference to `uiBoxAppend'
main.c:(.text+0x401): undefined reference to `uiNewGroup'
main.c:(.text+0x416): undefined reference to `uiGroupSetMargined'
main.c:(.text+0x42e): undefined reference to `uiBoxAppend'
main.c:(.text+0x433): undefined reference to `uiNewVerticalBox'
main.c:(.text+0x448): undefined reference to `uiBoxSetPadded'
main.c:(.text+0x45b): undefined reference to `uiGroupSetChild'
main.c:(.text+0x465): undefined reference to `uiNewButton'
main.c:(.text+0x47c): undefined reference to `uiBoxAppend'
main.c:(.text+0x486): undefined reference to `uiNewCheckbox'
main.c:(.text+0x49d): undefined reference to `uiBoxAppend'
main.c:(.text+0x4a2): undefined reference to `uiNewEntry'
main.c:(.text+0x4b7): undefined reference to `uiEntrySetText'
main.c:(.text+0x4cf): undefined reference to `uiBoxAppend'
main.c:(.text+0x4d9): undefined reference to `uiNewLabel'
main.c:(.text+0x4f0): undefined reference to `uiBoxAppend'
main.c:(.text+0x4f5): undefined reference to `uiNewHorizontalSeparator'
main.c:(.text+0x50c): undefined reference to `uiBoxAppend'
main.c:(.text+0x511): undefined reference to `uiNewDatePicker'
main.c:(.text+0x528): undefined reference to `uiBoxAppend'
main.c:(.text+0x52d): undefined reference to `uiNewTimePicker'
main.c:(.text+0x544): undefined reference to `uiBoxAppend'
main.c:(.text+0x549): undefined reference to `uiNewDateTimePicker'
main.c:(.text+0x560): undefined reference to `uiBoxAppend'
main.c:(.text+0x565): undefined reference to `uiNewFontButton'
main.c:(.text+0x57c): undefined reference to `uiBoxAppend'
main.c:(.text+0x581): undefined reference to `uiNewVerticalBox'
main.c:(.text+0x596): undefined reference to `uiBoxSetPadded'
main.c:(.text+0x5ae): undefined reference to `uiBoxAppend'
main.c:(.text+0x5b8): undefined reference to `uiNewGroup'
main.c:(.text+0x5cd): undefined reference to `uiGroupSetMargined'
main.c:(.text+0x5e5): undefined reference to `uiBoxAppend'
main.c:(.text+0x5ea): undefined reference to `uiNewVerticalBox'
main.c:(.text+0x5ff): undefined reference to `uiBoxSetPadded'
main.c:(.text+0x612): undefined reference to `uiGroupSetChild'
main.c:(.text+0x621): undefined reference to `uiNewSpinbox'
main.c:(.text+0x641): undefined reference to `uiSpinboxOnChanged'
main.c:(.text+0x65c): undefined reference to `uiBoxAppend'
main.c:(.text+0x66b): undefined reference to `uiNewSlider'
main.c:(.text+0x68b): undefined reference to `uiSliderOnChanged'
main.c:(.text+0x6a6): undefined reference to `uiBoxAppend'
main.c:(.text+0x6ab): undefined reference to `uiNewProgressBar'
main.c:(.text+0x6cd): undefined reference to `uiBoxAppend'
main.c:(.text+0x6d7): undefined reference to `uiNewGroup'
main.c:(.text+0x6ec): undefined reference to `uiGroupSetMargined'
main.c:(.text+0x704): undefined reference to `uiBoxAppend'
main.c:(.text+0x709): undefined reference to `uiNewVerticalBox'
main.c:(.text+0x71e): undefined reference to `uiBoxSetPadded'
main.c:(.text+0x731): undefined reference to `uiGroupSetChild'
main.c:(.text+0x736): undefined reference to `uiNewCombobox'
main.c:(.text+0x74b): undefined reference to `uiComboboxAppend'
main.c:(.text+0x75c): undefined reference to `uiComboboxAppend'
main.c:(.text+0x76d): undefined reference to `uiComboboxAppend'
main.c:(.text+0x785): undefined reference to `uiBoxAppend'
main.c:(.text+0x78a): undefined reference to `uiNewEditableCombobox'
main.c:(.text+0x79f): undefined reference to `uiComboboxAppend'
main.c:(.text+0x7b0): undefined reference to `uiComboboxAppend'
main.c:(.text+0x7c1): undefined reference to `uiComboboxAppend'
main.c:(.text+0x7d9): undefined reference to `uiBoxAppend'
main.c:(.text+0x7de): undefined reference to `uiNewRadioButtons'
main.c:(.text+0x7f3): undefined reference to `uiRadioButtonsAppend'
main.c:(.text+0x804): undefined reference to `uiRadioButtonsAppend'
main.c:(.text+0x815): undefined reference to `uiRadioButtonsAppend'

**Comment by andlabs** [comment]
Put the .c file *before* the libraries, not after. (Also you don't need the GTK+ `pkg-config`.)

**Comment by amar-laksh** [comment]
Seriously, I am ashamed thanks!
