### ISSUE TITLE
uiArea keyboard layout on Mac

### ISSUE THREAD

**Issue by mischnic** [andlabs/libui#334]
An issue I'm having on macOS (not tested on other platforms):
`uiAreaKeyEvent.Key` isn't using the current keyboard layout but the english one

**Comment by andlabs** [comment]
uiAreaKeyEvent.Key represents physical keys, so when it returns `'a'` it means the key that is where `'a'` would be on a US QWERTY keyboard. There are issues for translating physical keys to layout-specific keys, but I forget what they are now.

**Comment by mischnic** [comment]
is part of #329 already
