### ISSUE TITLE
Setup a Patreon

### ISSUE THREAD

**Issue by steelbrain** [andlabs/libui#335]
Hi @andlabs 

I love your work and would like to support it. Could you setup a Patreon or some other service out there that works similarly?

This project has an amazing idea and we'd hate to have it lose it's fire. Please continue the good work

**Comment by archcorsair** [comment]
I second this, would make for a great alternative to other **_bulky_** UI options out there!

**Comment by andlabs** [comment]
Thanks everyone, but I've decided to decline monetary donations at this time.
