### ISSUE TITLE
Support Android and iOS

### ISSUE THREAD

**Issue by DemiMarie** [andlabs/libui#35]
It would be nice to support iOS and Android devices as well.

**Comment by andlabs** [comment]
iOS and Android have very different design paradigms and widgets that do not match with libui's. Making something like this would be very difficult and very clunky.

**Comment by drbo** [comment]
That makes sense.  Perhaps a new library that abstracts between Android, iOS, and (possibly) Windows Runtime would be good for someone to create.

**Comment by psrafo** [comment]
@drbo you can start libui-mobile project with equivalent API.

**Comment by andlabs** [comment]
Merged with #327.
