### ISSUE TITLE
Context menu control

### ISSUE THREAD

**Issue by endoffile78** [andlabs/libui#352]
A control where when the user right clicks on something a menu will popup. It could be very similiar to the dropdown api.

**Comment by mischnic** [comment]
Are you thinking of a specific *control* (how should that look like) or the possibility to add a context menu to every control.

**Comment by endoffile78** [comment]
I was thinking something like [https://developer.gnome.org/gtkmm-tutorial/stable/figures/treeview_popup.png.en](this). Whenever you right click on any control you could get a context menu.

**Comment by andlabs** [comment]
Duplicate of #321 (though I forgot to list right-click menus there)

Not sure about *any* control, though.
