### ISSUE TITLE
How to retrieve date/time from an uiDateTimePicker instance?

### ISSUE THREAD

**Issue by LumingYin** [andlabs/libui#360]
It is possible to get text out of uiEntry instances with uiEntryText, but how would I be able retrieve date/time from an uiDateTimePicker instance?

**Comment by parro-it** [comment]
It's not implemented yet. See this PR: #297

**Comment by andlabs** [comment]
Duplicate of #309

**Comment by andlabs** [comment]
probably the wrong duplicate issue but meh

**Comment by parro-it** [comment]
Hey is this a new GH feature? Awesome!

![image](https://user-images.githubusercontent.com/11197111/39642912-65df1516-4fd3-11e8-82ee-2fb364c4d86f.png)
