### ISSUE TITLE
use of double underscore and underscore lettre prefix is reserved!

### ISSUE THREAD

**Issue by informatimago** [andlabs/libui#362]
__LIBUI_UI_H__ and _UI_EXTERN are identifiers that are reserved for the compiler. User programs must not use such identifiers! cf. the ANSI C standards, or http://c-faq.com/decl/namespace.html

UI_EXTERN or LIBUI_UI_H are perfectly good replacements.
(and similarly for all the others, such as _UI_ENUM, etc).

**Comment by parro-it** [comment]
Duplicate of https://github.com/andlabs/libui/issues/23

**Comment by informatimago** [comment]
Oops, sorry.

**Comment by andlabs** [comment]
Closed  as duplicate
