### ISSUE TITLE
Feature: Disable a control

### ISSUE THREAD

**Issue by LordZane** [andlabs/libui#409]
[GtkWidget](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-sensitive)
[NSControl](https://developer.apple.com/documentation/appkit/nscontrol/1428970-isenabled)
Not sure what framework libui uses on windows
[System.Windows.Forms.Control](https://msdn.microsoft.com/en-us/library/system.windows.forms.control.enabled(v=vs.110).aspx)
[UIElement (WPF)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.isenabled?view=netframework-4.7.2#System_Windows_UIElement_IsEnabled)

**Comment by mischnic** [comment]
Do you know about these functions?
```c
int uiControlEnabled(uiControl *);
void uiControlEnable(uiControl *);
void uiControlDisable(uiControl *);
```

**Comment by LordZane** [comment]
Oh no, sorry I didn't. It seems the bindings I'm using (rust) don't have this implemented yet. I'll make an issue over there, thanks for letting me know these exist
