### ISSUE TITLE
Add libui to vcpkg

### ISSUE THREAD

**Issue by CosmicBagel** [andlabs/libui#428]
For those who are unaware vcpkg is a cross-platform (Windows, Mac OS, Linux) c++ package manager that has gained decent traction, and has well surpassed the number of packages the conan provides. However, libui is sadly missing, and it would be nice to see it up there.

https://github.com/Microsoft/vcpkg

**Comment by ebraminio** [comment]
Is there now https://github.com/Microsoft/vcpkg/tree/master/ports/libui and can be closed :)
