### ISSUE TITLE
Tracking issue for replacing AppVeyor with Azure Pipelines

### ISSUE THREAD

**Issue by andlabs** [andlabs/libui#449]
more comparable to travis but for windows than appveyor is, so...

- [x] Test that this is feasible
- [x] Actually do the switch

**Comment by msink** [comment]
Didn't try it, but seems that msvc2017 and msvc2015 builds can be moved - so build will take about 10 minutes instead of 30.
Msvc2013 and msys2 should still live on Appveyor.

**Comment by andlabs** [comment]
MinGW might be feasible. The thing I still haven't figured out is 32-bit builds on any platform.

**Comment by msink** [comment]
I think MSYS2-MinGW build will be faster on Appveyor - because it is preinstalled, on Azure it should be installed first, and installation will take more time than build.

**Comment by andlabs** [comment]
Oh, I see. Noted.

**Comment by andlabs** [comment]
Actually, the MSVC 2017 image [already comes with MinGW-w64](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md#mingw) [as installed by Chocolatey](https://chocolatey.org/packages/mingw) [using this script](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/scripts/Installers/Install-MinGW.ps1), which also installs 32-bit MinGW-w64 in a separate location. The only problem is finding out what that location is, [and there is no real good way to do that with Chocolatey](https://superuser.com/questions/786024/is-there-a-way-to-list-chocolatey-packages-with-their-install-directory) (and the location has changed in the past, [which broke Azure Pipelines at one point](https://github.com/Microsoft/azure-pipelines-image-generation/issues/355)).

For now, we could just combine the Chocolatey install script (the `.ps1` file on the Chocolatey page I linked) with the Azure Pipelines script to get the proper paths:

```powershell
$whichMinGW = "mingw32" # or "mingw64"
$chocopath = where.exe choco.exe | Get-Item
$chocopath = Join-Path $chocopath.Directory "install" $whichMinGW "bin"
$chocopath = Join-Path $chocopath "mingw32" # or: $chocopath = Join-Path $chocopath "mingw64"
$chocopath = Join-Path $chocopath "bin"
echo "##vso[task.prependpath]$chocopath"
```

though I haven't tried this yet.

The hosted image documentation (the first link in this post) could be a lot more clear about these things. I'll file a bug with them. It also should be a bit more clear about MinGW-w64 version numbers, because they are confusing, but that's probably a Chocolately problem more than an Azure Pipelines problem.

I'll still need AppVeyor for VS2013, but only for VS2013.

**Comment by msink** [comment]
[MinGW-w64](https://mingw-w64.org/doku.php) and [MSYS2-mingw](https://www.msys2.org/) are different distributions, or flavors, not always compatible - so if you will set build by w64 - it will be good for w64 users, they will not need build from source :)

For my personal needs - my Kotlin binding is based on MSYS2.
But it anyway already based on separate Appveyoe build - for now 4.1 with applied [Open folder path](https://github.com/msink/libui/commit/33d8f2b0d9c10cbfc70edee17a1cf33455306c22)

**Comment by andlabs** [comment]
Wait, how are they different? I'm pretty sure the MinGW-w64 32-bit and 64-bit Shell options in the MSYS2 distribution will give you the same MinGW-w64 as non-MSYS2 MinGW-w64s...?

**Comment by msink** [comment]
I'm not big expert in this area, but AFAIK they use different exception formats.
I personally never used anything but MSYS2-mingw.

**Comment by andlabs** [comment]
```
DEBUG:    3+  >>>> ls "$env:ChocolateyInstall\lib\mingw\tools\install"


    Directory: C:\ProgramData\chocolatey\lib\mingw\tools\install


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        5/12/2018   7:29 AM                mingw64                                                               
DEBUG:    4+  >>>> where.exe mingw32-make.exe | Write-Host
C:\ProgramData\Chocolatey\bin\mingw32-make.exe
DEBUG:    5+  >>>> where.exe gcc.exe | Write-Host
C:\ProgramData\Chocolatey\bin\gcc.exe
C:\Strawberry\c\bin\gcc.exe
```

Something is deeply wrong here.

**Comment by andlabs** [comment]
Oh right, I forgot about MinGW-w64 on Linux! And Meson ships with cross-files for this specifically, so we might have a way out after all...

**Comment by andlabs** [comment]
...and it's too old. Oh well.

**Comment by andlabs** [comment]
I will say that with meson/ninja the individual builds are somehow much faster, so that's a plus.

**Comment by andlabs** [comment]
I'll test binaries separately.
