### ISSUE TITLE
Build warnings (again) with cmake under Mojave and cmake 3.13.4

### ISSUE THREAD

**Issue by teras** [andlabs/libui#458]
Following the information here, https://github.com/andlabs/libui/issues/442 , I was trying to build libui from sources. 
Indeed the old error message disappears, but a new warning arrives.
The new warning message is:

``
-- Configuring done
CMake Warning (dev):
  Policy CMP0068 is not set: RPATH settings on macOS do not affect
  install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, the install_name fields for
  the following targets are still affected by RPATH settings:

   libui

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/teras/Sources/libui/build
``

The library builds fine, but shouldn't this warning been taken into account?

**Comment by andlabs** [comment]
Yes, but I have no idea how, and the suggested help text doesn't actually help either. I'd need a different explanation that takes what I'm doing into account, because I don't understand what actions I should take.

**Comment by mischnic** [comment]
As far as I can tell (and test), libui isn't affected by this because `CMAKE_INSTALL_NAME_DIR` isn't used (see official description below).

To silence the warning by opting into the new behaviour:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c7193fbb..98d262f4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,7 @@
 # 3 june 2016
 # see https://cmake.org/gitweb?p=cmake.git;a=commit;h=95cdf132489c79e88a10fdf7a7566fa002c7680b (thanks ngladitz in irc.freenode.net/#cmake)
 cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)
+cmake_policy(SET CMP0068 NEW) # > `RPATH` settings on macOS do not affect `install_name` <

 # TODOs
 # - silence entering/leaving messages?
```


<details>
<summary> Policy description </summary>

```
CMP0068
-------

``RPATH`` settings on macOS do not affect ``install_name``.

CMake 3.9 and newer remove any effect the following settings may have on the
``install_name`` of a target on macOS:

* ``BUILD_WITH_INSTALL_RPATH`` target property
* ``SKIP_BUILD_RPATH`` target property
* ``CMAKE_SKIP_RPATH`` variable
* ``CMAKE_SKIP_INSTALL_RPATH`` variable

Previously, setting ``BUILD_WITH_INSTALL_RPATH`` had the effect of
setting both the ``install_name`` of a target to ``INSTALL_NAME_DIR``
and the ``RPATH`` to ``INSTALL_RPATH``.  In CMake 3.9, it only affects
setting of ``RPATH``.  However, if one wants ``INSTALL_NAME_DIR`` to
apply to the target in the build tree, one may set
``BUILD_WITH_INSTALL_NAME_DIR``.

If ``SKIP_BUILD_RPATH``, ``CMAKE_SKIP_RPATH`` or
``CMAKE_SKIP_INSTALL_RPATH`` were used to strip the directory portion
of the ``install_name`` of a target, one may set ``INSTALL_NAME_DIR=""``
instead.

The ``OLD`` behavior of this policy is to use the ``RPATH`` settings for
``install_name`` on macOS.  The ``NEW`` behavior of this policy is to ignore
the ``RPATH`` settings for ``install_name`` on macOS.

This policy was introduced in CMake version 3.9.  CMake version
3.13.3 warns when the policy is not set and uses ``OLD`` behavior.
Use the ``cmake_policy()`` command to set it to ``OLD`` or ``NEW``
explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.
```

</details>

**Comment by andlabs** [comment]
The switch has happened; closing.

And yeah, after seeing the rpath settings being split in meson, I think I understand this policy a bit better now, but too late for that :/
