### ISSUE TITLE
[Question] CMake deprecated?

### ISSUE THREAD

**Issue by tan-wei** [andlabs/libui#469]
It seems almost all the `CMakeLists.txt` are removed in the project now (`17486fd17593510452939a120dc9a4e6fbe5cf80`). But I can find that CMake was used before. It seems `meson` is the replacement.

**Comment by andlabs** [comment]
Yes, that is correct.

**Comment by tan-wei** [comment]
> 
> 
> Yes, that is correct. The migration to meson is complete; whatever CMakeLists files you may still find on master are remnants of experiments.

Got it. From `Readme.md` we can see:

> The build system has been switched to Meson. See below for instructions. This change was made because the previous build system, CMake, caused countless headaches over trivial issues. Meson was chosen due to how unproblematic setting up libui's build just right was, as well as having design goals that are by coincidence closely aligned with what libui wants.

Bad news for users who depend on `CMake`, but I think they can get a valid `CMakeLists.txt` from project `vcpkg`. Thanks for your reply.
