### ISSUE TITLE
onShouldQuit handler should be called by uiQuit(), not just by the menu item Quit

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#49]
as the title sais. Otherwise you can set up fancy onshouldquit handlers, and they will not be called because the user closed the window instead of closing the app through File->Quit

**Comment by aoloe** [comment]
see also #32.
as said in the other ticket, i would personally try to solve this issue by removing the magic in file > quit and adding a simple way to attach the quit behavior to menu item.

**Comment by andlabs** [comment]
This has to do with whether event handlers should be triggered progammatically. There's another bunch of issues for that, but I'll merge the whole set together later.

**Comment by andlabs** [comment]
Merged with #326.
