### ISSUE TITLE
Darwin: Cannot call uiQuit() before calling uiMain()

### ISSUE THREAD

**Issue by xobs** [andlabs/libui#495]
On Linux and Windows, it is possible to call `uiQuit()` prior to calling `uiMain()`.  This causes the program to immediately quit after one run of the program loop.

In contrast, in Darwin the initial `uiQuit()` appears to be ignored if it's called prior to `uiMain()`.

This behavior is used in functional tests, which shouldn't run forever yet need to poll the main loop.

**Comment by andlabs** [comment]
Good to know. In Haiku I think it does worse. I'll have to figure out what to do about that.

**Comment by xobs** [comment]
I'm not sure.  I'm submitting fixes to the Rust bindings, and came across this as part of their doctests.  They're on a relatively old version of libui (pre-Meson), however I did confirm that this happens with the latest `master` branch (from 1 January).

Which behavior is correct?

1. `uiQuit()` before `uiStart()` is ignored
2. `uiQuit()` before `uiStart()` calls the main loop once
3. `uiQuit()` before `uiStart()` immediately quits when `uiStart()` is called

I notice that GTK functions by firing off a thread.  Perhaps Darwin could do that too?

**Comment by xobs** [comment]
> I thought I had this behavior as a test case (remodel branch)?

I thought I'd give the `remodel` branch a try.  There are definitely a lot of changes, but I'm unable to actually test it since the Windows port seems incomplete (e.g. `windows/meson.build` references `windows/alloc.cpp`, which doesn't exist).

**Comment by andlabs** [comment]
Yeah, it's nowhere near ready yet. I've been preoccupied, sorry.

**Comment by andlabs** [comment]
Ah; Haiku:

```
// TODO if this is called beofre uiMain(), uiprivApp will be deleted; either ban doing this outright or catch this scenario
```

Which is not good when libui needs that object to exist to call uiMain()...

**Comment by andlabs** [comment]
I've fixed this in remodel by banning use of uiQuit() before uiMain() in general.
