### ISSUE TITLE
how to handle keyboard events with ui?

### ISSUE THREAD

**Issue by sergeytol** [andlabs/libui#499]
Is it possible to handle onKeyDown() and other keyboard events with ui somehow? Are there any examples of code?

**Comment by sergeytol** [comment]
Sorry it was question for Go ui

**Comment by rubyFeedback** [comment]
It may still be interesting indirectly! For example I use ruby-libui bindings
but just hearing how problems are solved in other programming
language CAN be useful. We sort of need to co-share information,
a bit similar to how StackOverflow can be used (for example I learned
a LOT for ruby-gtk just reading python-gtk specific stuff :D )
