### ISSUE TITLE
how to get the value of an EditableCombobox

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#51]
seems like there is no way to access the edited value of an EditableCombobox? Maybe a get/setvalue pair for comboboxes would be good, that would return whatever string is visible to the user (edited or not)

**Comment by andlabs** [comment]
That is precisely why I am going to split uiCombobox and uiEditableCombobox later today.

**Comment by andlabs** [comment]
Now in as `uiEditableComboboxText()`.
