### ISSUE TITLE
New Ruby Library

### ISSUE THREAD

**Issue by kojix2** [andlabs/libui#519]
Hi @andlabs and libui developers!

Thanks for this awesome library! 
I wanted to let you know that there are new [Ruby bindings](https://github.com/kojix2/libui) for it.

Compared to [libui-ruby](https://github.com/jamescook/libui-ruby), it has the following features.

1. The package contains shared libraries ([libui.so, libui.dylib, libui.dll](https://github.com/andlabs/libui/releases/tag/alpha4.1), and [README](https://github.com/andlabs/libui/blob/master/README.md) of libui). (Please notify me if there are any problems with redistribution.)
2. Uses the Ruby standard library [fiddle](https://github.com/ruby/fiddle) for C function calls. 
3. Syntax is more Ruby-like.

If you have any feedback, let me know or feel free to create an [issue](https://github.com/kojix2/libui/issues) in the project for it. Thanks!

**Comment by andlabs** [comment]
I'll add it to the README later

**Comment by kojix2** [comment]
Thank you!!

**Comment by kojix2** [comment]
Thank you!
