### ISSUE TITLE
Another C++ binding

### ISSUE THREAD

**Issue by sy-borg** [andlabs/libui#537]
Hi there, I made another C++ binding, you can find it here https://codeberg.org/trill/libuipp. It is a header only library (for easy integration) and requires C++20 because of concepts. See here https://codeberg.org/trill/libuipp/src/branch/master/src/main.cpp for a simple sample and here https://codeberg.org/trill/libuipp/media/branch/master/sample.png?raw=true what it looks like on Linux.

Thank you for this library.

**Comment by SteffenL** [comment]
Since all of the provided links return 404, may I suggest closing this issue?

**Comment by sy-borg** [comment]
Yes sure.

**Comment by cody271** [comment]
@sy-borg What happened to these new C++ bindings? Repo was deleted?

**Comment by sy-borg** [comment]
Yes, I was cleaning up my repos.
