### ISSUE TITLE
libui seems to arbitrarily pick which screen to spawn a window on

### ISSUE THREAD

**Issue by iKlsR** [andlabs/libui#54]
I'm on ubuntu with dual monitors and I would expect that my program would be created on my primary monitor initially whereas it seems to pick one or the other.

**Comment by andlabs** [comment]
I leave that up to GTK+ to decide, and I believe GTK+ leaves it up to your window manager to decide, but I'm not sure about that part. You can check the GtkWindow source code if you want; I use `gtk_window_present()` to show a window.

**Comment by iKlsR** [comment]
Right, looks like my wm is doing the magics. https://askubuntu.com/questions/120725/open-new-windows-on-main-screen-in-kde-two-screen-setup
