### ISSUE TITLE
windows: controlgallery crashes in edit field on enter key (EDIT: and spinboxes too)

### ISSUE THREAD

**Issue by Extrawurst** [andlabs/libui#55]
the example crashes when you hit enter in the entry box:

```
...
entry = uiNewEntry();
...
```

at least on osx that does not happen

**Comment by andlabs** [comment]
This is a bug that has to do with legacy stuff in the Windows edit control dating back to Windows 1.0. There's a TODO about it somewhere in the source; more details [here](http://blogs.msdn.com/b/oldnewthing/archive/2007/08/20/4470527.aspx). I have to figure out how to fix it.

**Comment by mellinoe** [comment]
For more data, the example crashes if I hit enter anywhere, not just the "Entry" box.

**Comment by andlabs** [comment]
Probably `IsDialogMessage()` related then? I wonder if I can follow the message chain when this happens...

**Comment by emersion** [comment]
Also happens when pressing Esc.

**Comment by andlabs** [comment]
Same root cause (Enter is to OK as Esc is to Cancel).

**Comment by lxn** [comment]
In the `WM_COMMAND` handler in `windowWndProc`, `IDOK` and `IDCANCEL` currently get through to `runMenuEvent`, where they have a date with `implbug`.
