### ISSUE TITLE
can the window parameter for system dialogs be NULL?

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#64]
concerns (for now) these functions:
_UI_EXTERN char *uiOpenFile(uiWindow *parent);
_UI_EXTERN char *uiSaveFile(uiWindow *parent);
_UI_EXTERN void uiMsgBox(uiWindow *parent, const char *title, const char *description);
_UI_EXTERN void uiMsgBoxError(uiWindow *parent, const char *title, const char *description);

can the parent parameter be NULL, i.e. parentless dialogs?

**Comment by andlabs** [comment]
No, not in the current version. Some systems, like GTK+, will complain on stderr if you try to have an ownerless dialog. Others, like OS X, require ownerless dialogs o be *application*-modal. Dialogs are a giant beast that I have no idea how to fully tackle; I'll have to write up something about it.

**Comment by gnarz** [comment]
this is not a problem, I just wanted to know whether you intended to allow this.

**Comment by andlabs** [comment]
I'd like to allow it (it'd make a bunch of things easier), but then GTK+ will spit out warnings on stderr which will lead to more bug reports. I'm not sure which is the lesser of two evils =P

**Comment by andlabs** [comment]
Replaced with #314.
