### ISSUE TITLE
A method: uiWindowGetChild(uiWindow *w); ??

### ISSUE THREAD

**Issue by amar-laksh** [andlabs/libui#66]
Can't seem to find such a method in the library. It could return an array of child windows, widgets etc.

**Comment by pcwalton** [comment]
Ideally this could be a method on `uiControl`, to allow fetching the children of *any* control. This would improve memory management.

**Comment by andlabs** [comment]
Probably `uiControlForAllChildren()` with a custom callback, to avoid memory allocations...

**Comment by SevenBits** [comment]
Some sort of structure to allow iteration of children might be useful as well (or it could be done by that function).

**Comment by andlabs** [comment]
Merged with #309.
