### ISSUE TITLE
Use uilib as a library for own applications? 

### ISSUE THREAD

**Issue by kylenahas** [andlabs/libui#67]
Sorry for the noob GNU make question, and this deserves to be closed right away, but I can't quite figure out how to link my own code against libui, using it as a library. Some updated documentation might be nice regarding this. I'm running on OS X.

**Comment by andlabs** [comment]
You take the generated `out/libui.A.dylib` and link your program against it. How do you want to distribute your final app?

**Comment by kylenahas** [comment]
I plan on distributing it as source for users on other platforms to compile. 

When I compile my program using `$ gcc -Wall -g main.c -o run libui.A.dylib` (which I did before asking, sorry for not including that.) I get this error when executing the program 


> $ ./run
> dyld: Library not loaded: @rpath/libui.A.dylib
>   Referenced from: /Users/kylenahas/Projects/radarcom/./run
>   Reason: image not found
> Trace/BPT trap: 5


Again, sorry for asking this here. I'm not sure this is the right channel, but if not could you please point me in the right direction? Thanks so much. Btw, your library looks fantastic. I've been recommending it to all my friends and coworkers. Can't wait to start using it. :)

**Comment by andlabs** [comment]
Oh, you also need to set the rpath on your executable with `-Wl,-rpath,@executable_path`

**Comment by kylenahas** [comment]
Fantastic, that worked! Thanks again!

**Comment by andlabs** [comment]
No problem; good luck :)

**Comment by andlabs** [comment]
I think this is fixed...? Building instructions are definitely constantly in my mind.
