### ISSUE TITLE
Why didn't you use XLib or XCB?

### ISSUE THREAD

**Issue by Supermath101** [andlabs/libui#68]
GTK+ isn't native. Some binding of X11 is. Why didn't you use that? Your description is:

> Simple and portable (but not inflexible) GUI library in C that uses the **native** GUI technologies of each platform it supports

**Comment by andlabs** [comment]
xlib and xcb are both libraries for dealing with X11 directly; if I used them only I would have to implement all the widgets myself.

GTK+ and Qt are the closest thing to native that modern Unix desktops have. They do all the work of actually making the widgets and most programs use one or the other.

**Comment by Supermath101** [comment]
And what's the problem with _implementing all the widgets yourself_?

**Comment by andlabs** [comment]
Then I would be reimplementing GTK+ and Qt, but poorly, and that's not the goal.

Also [here's what happened when GTK+ actually used X11 windows for **everything** instead of just toplevel windows](https://people.gnome.org/~alexl/flicker.ogg).
