### ISSUE TITLE
Treeview widget

### ISSUE THREAD

**Issue by zwlxt** [andlabs/libui#71]
When I searched through the repository using keyword Tree, I found that

> // On GTK+, uiTableModel is a GtkTreeModel.

But what about on Windows? Are there any alternatives?

**Comment by andlabs** [comment]
That stuff was all WIP and only worked on GTK+. The real Tree will come after the next packaged release, and I'm not sure how that will work.

**Comment by zwlxt** [comment]
Thanks for your reply :), I really appreciate your great work.
