### ISSUE TITLE
get rid of uiAreaDrawParams.AreaWidth and AreaHeight

### ISSUE THREAD

**Issue by gnarz** [andlabs/libui#73]
instead, for non-scrolling areas always set the clip rectangle to (0, 0) - (width, height)
This way the handler doesn't have to know whether it deals with a scrolling or non-scrolling area.

**Comment by andlabs** [comment]
The clip rectangle is defined by the operating system and may be smaller than the size of the area. For instance, if you drag a window over an area, only the part that is covered will need redrawing, so only that will be given to you as the clip.

**Comment by gnarz** [comment]
Maybe then the other way round, make Area* return the allocated size for scrolling areas. It is somewhat weird that those fields are only available for non scrolling areas...

Von meinem iPhone gesendet

**Comment by andlabs** [comment]
You mean to just return the size requested with SetSize()? That's a possibility, yes...

**Comment by andlabs** [comment]
Migrated to #82.
