### ISSUE TITLE
Entering a value in spinboxes crashes the program

### ISSUE THREAD

**Issue by joa-quim** [andlabs/libui#77]
Just build the examples/histogram and make an Enter in any of the spinboxes. Program crashes right away.

**Comment by andlabs** [comment]
What OS?

**Comment by joa-quim** [comment]
Sorry forgot that. Windows

**Comment by andlabs** [comment]
Duplicate of #55. Spinboxes and entries use the same edit controls that have this issue. Now I just wish github had issue prioritizing, since that'll have to become a serious issue since a lot of people are getting it...
