### ISSUE TITLE
request: Trackpad gestures

### ISSUE THREAD

**Issue by pcwalton** [andlabs/libui#81]
For http://github.com/servo/servo we need trackpad gestures in `uiArea`s in order to feel native. We also need support for the mouse wheel. There are two trackpad gestures we care about right now: scrolling (which can be unified with mouse wheel) and pinch-to-zoom.

Many other apps have support for trackpad gestures nowadays, so this should be useful functionality for more than just us.

**Comment by andlabs** [comment]
Right. I've never programmed for a before, so I'm not fully sure how it works. I can definitely look into it (if VirtualBox will let me do the trackpad gestures on VMs, at least).

As for scroll wheel events, I've been thinking about how to add them. Probably a new AreaHandler method

    int (*ScrollWheel)(uiAreaHandler *ah, uiArea *a, int horizontal, SomeNumericType amount, int byPages);

basing on https://blogs.msdn.microsoft.com/oldnewthing/20030807-00/?p=42963/ (positive amounts being right or down)

Not sure if this is sufficient.

**Comment by pcwalton** [comment]
From experience I can tell you that the annoying bit will be mapping the units of one platform to the other. IIRC on Mac you get pixels for wheel/swipe events (as long as you use `scrollingDeltaX`/`scrollingDeltaY`; make sure to use these for proper accuracy!), while in GTK you get "lines", which don't have an obvious pixel mapping. I can look up the formula that we used in Servo if you like. I would suggest exposing pixels rather than lines to the API consumer, as this is more broadly useful when panning e.g. an image or other nontextual content.

**Comment by andlabs** [comment]
Right, and the Windows formula uses lines. Feel free to pull out that formula; I'll do my own research in the meantime.

I forgot to mention: the int return value is 1 to indicate "you handled this event" or 0 to say "you didn't; let the OS scrolling do their thing instead"

**Comment by andlabs** [comment]
Merged with #329.
