### ISSUE TITLE
possibility: uiArea sizing and scrolling changes

### ISSUE THREAD

**Issue by andlabs** [andlabs/libui#82]
Migrating in #73 and https://github.com/andlabs/ui/issues/116.

Instead of maintaining separate non-scrolling and scrolling uiAreas, have just scrolling ones. The width and height can be independently set to affect horizontal and vertical scrolling.

If the width of a uiArea is <= 0 (or should it be < instead?), the uiArea is as wide as the available space, as in a non-scrolling uiArea. Otherwise, the uiArea will scroll to that width.

Likewise for height and OpenGL uiAreas.

Probably also introduce uiAreaSize() to get the current size and uiAreaHandler.SizeChanged() as an event to catch when the size has changed in the case of a <=0 dimension.

The only problem platform here is GTK+; I'm not sure how to make GtkScrolledWindow and GtkViewport and GtkDrawingArea play nice with this design.

**Comment by gnarz** [comment]
also, changing the width and height of an area after creation would be nice. I mean the size of the drawing area, not the size of the visible area.

**Comment by andlabs** [comment]
Note to self: also need `uiAreaSetMinSize()` or something to that effect.

**Comment by andlabs** [comment]
Merged with #329.
