### ISSUE TITLE
request: Support for keyboard shortcuts/accelerators in menus

### ISSUE THREAD

**Issue by pcwalton** [andlabs/libui#89]
This is needed to feel native on all platforms.

**Comment by andlabs** [comment]
That is planned, yes. I need to figure out how menus are going to work.

Potential problem: on OS X, things like copy and paste not only require accelerators to be hooked, but also hooked to specific selectors (`copy:`, for instance). uiArea will probably need to have special events for those, but that raises the question of how to do the same on other platforms. More predefined menu items?

**Comment by kainjow** [comment]
Just extend the built-in menu types (e.g. `uiMenuAppendCopyItem`) but for OS X set the target to nil to use the first responder.

**Comment by aoloe** [comment]
somehow, i would prefer being able to attach the built-in action to the same action attached to the menu item.

**Comment by andlabs** [comment]
@aoloe I don't understand what you mean; could you clarify your comment please?

**Comment by aoloe** [comment]
i would prefer not to have a uiMenuAppendCopyItem in the same way i'm not fond of uiMenuAppendQuitItem (#32).

a quick and dirty "draft" of my idea would be:

	item = uiMenuAppendItem(menu, "Quit");
	uiMenuItemOnClicked(item, quitClicked, NULL);
        uiSystemActionQuit(quitClicked);

	item = uiMenuAppendItem(menu, "Copy");
	uiMenuItemOnClicked(item, copyClicked, NULL);
        uiSystemActionCopy(copyClicked);

i don't know if it's clearer this way or an `uiSystemActionQuit()` function is a good idea... but the main idea is that i'd prefer to get more transparency in what actions are triggered. Currently the Quit action is somehow a "magic" one...
It would be the same for the Copy one...

**Comment by andlabs** [comment]
Ah. So how would your event work for copying while focus is on a uiEntry? Would I have to override the entry controls to intercept the request to copy?

Also I forget how accelerators are done on GTK+; I think GtkActionGroup...

**Comment by aoloe** [comment]
my comment was about the idea of adding one more buil-in action, not about adding shortcuts...
i tried to check how qt applications manage copy but could not find anything usable for helping in this matter, sorry....

**Comment by mischnic** [comment]
+1 (or rather +100) for "to feel native"

Here is the macOS part (all native actions I could find) :
```objc
	case typeCopy:
		item->item = [[NSMenuItem alloc] initWithTitle:toNSString(name) action:@selector(copy:) keyEquivalent:@"c"];
		[m->menu addItem:item->item];
		break;
	case typePaste:
		item->item = [[NSMenuItem alloc] initWithTitle:toNSString(name) action:@selector(paste:) keyEquivalent:@"v"];
		[m->menu addItem:item->item];
		break;
	case typeCut:
		item->item = [[NSMenuItem alloc] initWithTitle:toNSString(name) action:@selector(cut:) keyEquivalent:@"x"];
		[m->menu addItem:item->item];
		break;
	//name is ignored for undo and redo
	case typeUndo:
		item->item = [[NSMenuItem alloc] initWithTitle:@"" action:@selector(undo:) keyEquivalent:@"z"];
		[m->menu addItem:item->item];
		break;
	case typeRedo:
		item->item = [[NSMenuItem alloc] initWithTitle:@"" action:@selector(redo:) keyEquivalent:@"Z"];
		[m->menu addItem:item->item];
		break;
	case typeSelectAll:
		item->item = [[NSMenuItem alloc] initWithTitle:toNSString(name) action:@selector(selectAll:) keyEquivalent:@"a"];
		[m->menu addItem:item->item];
		break;
	case typeToogleFullscreen:
		item->item = [[NSMenuItem alloc] initWithTitle:@"Toggle Full Screen" action:@selector(toggleFullScreen:) keyEquivalent:@"f"];
		[m->menu addItem:item->item];
		break;
```

It works fine, but Unix and Windows support is of course missing (should all of these function be reimplemented ?).

**Comment by mischnic** [comment]
Regarding the naming: 
```c
uiMenuItem *uiMenuAppendItem(uiMenu *m, const char *name, int type);
```
(with type being a platform-independent enum) would require adding a function for every type (like `uiSystemActionCopy` or `uiMenuAppendCopyItem`).

**Comment by andlabs** [comment]
Replaced with #321.
