### ISSUE TITLE
BUILD EXAMPLE FAILED

### ISSUE THREAD

**Issue by topillar** [andlabs/libui#9]
C:\libui>mingw32-make -f GNUmakefile example EXAMPLE=controlgallery
mingw32-make[1]: 'out/libui.dll' is up to date.
main.c
examples/controlgallery/main.c(25): error C2198: 'uiOpenFile': too few arguments for call
examples/controlgallery/main.c(27): warning C4133: 'function': incompatible types - from 'char [17]' to 'uiWindow *'
examples/controlgallery/main.c(27): error C2198: 'uiMsgBoxError': too few arguments for call
examples/controlgallery/main.c(30): warning C4133: 'function': incompatible types - from 'char [14]' to 'uiWindow *'
examples/controlgallery/main.c(30): error C2198: 'uiMsgBox': too few arguments for call
examples/controlgallery/main.c(38): error C2198: 'uiSaveFile': too few arguments for call
examples/controlgallery/main.c(40): warning C4133: 'function': incompatible types - from 'char [17]' to 'uiWindow *'
examples/controlgallery/main.c(40): error C2198: 'uiMsgBoxError': too few arguments for call
examples/controlgallery/main.c(43): warning C4133: 'function': incompatible types - from 'char [46]' to 'uiWindow *'
examples/controlgallery/main.c(43): error C2198: 'uiMsgBox': too few arguments for call
examples/controlgallery/main.c(55): warning C4244: 'function': conversion from 'intmax_t' to 'int', possible loss of data
build/GNUbasemsvc.mk:64: recipe for target '.obj/examples_controlgallery_main.c.o' failed
mingw32-make[1]: *** [.obj/examples_controlgallery_main.c.o] Error 2
GNUmakefile:58: recipe for target 'example' failed
mingw32-make: *** [example] Error 2

**Comment by andlabs** [comment]
I still have not updated that example to use new API. It will be updated at a later date.
