### ISSUE TITLE
Request: Ncurses Backend

### ISSUE THREAD

**Issue by HalosGhost** [andlabs/libui#90]
All of the widgets supported in the current version of libui, can operate in ncurses.

Using ncurses applications is an absolute pleasure; _writing_ ncurses applications is an utter pain.

Having the ability to take one code base to generate a solid ncurses UI along with the GUI analogs in GTK and Qt would be _amazing_. Considering what may need to be done for ncurses, this may be a rather significant request. But, I would be incredibly excited for the possibility.

Perhaps something like [CDK](http://www.tldp.org/HOWTO/NCURSES-Programming-HOWTO/tools.html) would aid in the port.

**Comment by pcwalton** [comment]
I kind of wonder whether out-of-tree backends will be an inevitability if and when the library gains in popularity. (Android, iOS, HTML+CSS with Emscripten, curses, and/or a resurrected Haiku come to mind.) It's reasonable to divide platforms into in-tree Tier 1 and out-of-tree (or just unsupported/allowed to break) Tier 2, IMHO.

**Comment by andlabs** [comment]
(For what it's worth I do want to go back to Haiku someday, but that day will come when the new Haiku-specific APIs become stable and well-documented, without weird API turns all over the place.)

**Comment by andlabs** [comment]
Merged with #327.
