### ISSUE TITLE
Bug: sample applications not using MS Windows subsystem

### ISSUE THREAD

**Issue by SevenBits** [andlabs/libui#94]
On Windows, a console window appears when you run any of the sample programs. This is likely because the application is using the console subsystem instead of the MS Windows subsystem. In MinGW, you can change this with the `-mwindows` flag; not sure how to do this in MSVC though.

**Comment by andlabs** [comment]
Fixed in the cmake files already.

**Comment by andlabs** [comment]
Fixed for real.
