### ISSUE TITLE
add swift version.please

### ISSUE THREAD

**Issue by danwey** [andlabs/libui#99]
add swift version.please

**Comment by andlabs** [comment]
Did someone write Swift bindings that I can add to the list?

**Comment by TravisJoe** [comment]
I would like this also. Like Go a crossplatform UI framework (now that is is open sourced) is not available. Not have a UI at least on unix based systems holds me back from wanting to try to use swift.

I tried to search on google for Swift and Libui but only found a couple possible bits of information that ended in broken links.

**Comment by joaoventura** [comment]
Nothing stops anyone from starting his own bindings! Just check out the C source code, try to implement a minimal example with just a window with a label. Then check how swift interfaces with C and start implement something until you can do in swift what you've done with C. Then rinse and repeat until you get bored or you finish the implementation. Be practical and stop whining.. ;)

**Comment by andlabs** [comment]
If there are no existing Swift bindings then I will close this, as I have no plans on adding bindings directly to the libui repository. If someone else makes a Swift binding, please let me know so I can add it to the list of bindings in the README. Thanks!

**Comment by sclukey** [comment]
I've written bindings for Swift. It's [libui-swift](https://github.com/sclukey/libui-swift). Even though *technically* the binding is done with [clibui](https://github.com/sclukey/clibui), libui-swift is a wrapper that makes the library "Swifty" and makes the C<->Swift interactions not so much of a chore.

**Comment by andlabs** [comment]
Cool; I'll merge the README stuff soon. Thanks!
